In [166]:
import pandas as pd
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
import statistics as st

pd.options.display.max_rows = 200

In [58]:
df = pd.DataFrame()
for i in range(2,5):
    file_name = f"./round-{i}-island-data-bottle/prices_round_{i}_day_1.csv"
    df_day_i = pd.read_csv(file_name, sep=';')
    df = pd.concat([df, df_day_i])
    
df = df.sort_values(by='timestamp', ascending=True).reset_index()

In [59]:
file_name = f"./round-{2}-island-data-bottle/prices_round_{2}_day_1.csv"
df_day_2 = pd.read_csv(file_name, sep=';')

In [60]:
df_day_2.columns

Index(['timestamp', 'ORCHIDS', 'TRANSPORT_FEES', 'EXPORT_TARIFF',
       'IMPORT_TARIFF', 'SUNLIGHT', 'HUMIDITY', 'DAY'],
      dtype='object')

In [61]:
file_name = f"./round-{3}-island-data-bottle/prices_round_{3}_day_1.csv"
df_day_3 = pd.read_csv(file_name, sep=';')

In [62]:
df_day_3.columns

Index(['day', 'timestamp', 'product', 'bid_price_1', 'bid_volume_1',
       'bid_price_2', 'bid_volume_2', 'bid_price_3', 'bid_volume_3',
       'ask_price_1', 'ask_volume_1', 'ask_price_2', 'ask_volume_2',
       'ask_price_3', 'ask_volume_3', 'mid_price', 'profit_and_loss'],
      dtype='object')

In [63]:
file_name = f"./round-{4}-island-data-bottle/prices_round_{4}_day_1.csv"
df_day_4 = pd.read_csv(file_name, sep=';')

In [64]:
df_day_4

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
0,1,0,COCONUT,9999,200,NaN,NaN,NaN,NaN,10001,200,NaN,NaN,NaN,NaN,10000.0,0.0
1,1,0,COCONUT_COUPON,637,39,NaN,NaN,NaN,NaN,638,39,NaN,NaN,NaN,NaN,637.5,0.0
2,1,100,COCONUT,9999,104,9998.0,44.0,NaN,NaN,10000,104,10001.0,44.0,NaN,NaN,9999.5,0.0
3,1,100,COCONUT_COUPON,637,33,NaN,NaN,NaN,NaN,638,33,NaN,NaN,NaN,NaN,637.5,0.0
4,1,200,COCONUT,9998,133,9997.0,62.0,NaN,NaN,9999,133,10000.0,62.0,NaN,NaN,9998.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,1,999700,COCONUT_COUPON,681,46,NaN,NaN,NaN,NaN,682,46,NaN,NaN,NaN,NaN,681.5,0.0
19996,1,999800,COCONUT_COUPON,681,43,NaN,NaN,NaN,NaN,682,43,NaN,NaN,NaN,NaN,681.5,0.0
19997,1,999800,COCONUT,10134,122,10133.0,65.0,NaN,NaN,10136,181,NaN,NaN,NaN,NaN,10135.0,0.0
19998,1,999900,COCONUT_COUPON,682,36,NaN,NaN,NaN,NaN,683,36,NaN,NaN,NaN,NaN,682.5,0.0
19999,1,999900,COCONUT,10134,178,NaN,NaN,NaN,NaN,10136,120,10137.0,58.0,NaN,NaN,10135.0,0.0

In [65]:
df_day_3_pivoted = df_day_3.pivot(index='timestamp', columns='product', values='mid_price')
df_day_4_pivoted = df_day_4.pivot(index='timestamp', columns='product', values='mid_price')

In [66]:
df_day_3_pivoted.reset_index(inplace=True)
df_day_4_pivoted.reset_index(inplace=True)

In [67]:
df = pd.merge(df_day_2, df_day_3_pivoted, on='timestamp', how='outer')
df = pd.merge(df, df_day_4_pivoted, on='timestamp', how='outer')

In [68]:
columns_order = ['timestamp', 'ORCHIDS', 'TRANSPORT_FEES', 'EXPORT_TARIFF', 'IMPORT_TARIFF', 'SUNLIGHT', 'HUMIDITY', 'DAY']
product_columns = [col for col in df.columns if col not in columns_order]
columns_order.extend(product_columns)
df = df[columns_order]

In [69]:
df.to_csv('day_1_consolidated.csv', index=False)

In [70]:
df = pd.read_csv('day_1_consolidated.csv')

In [71]:
df

,timestamp,ORCHIDS,TRANSPORT_FEES,EXPORT_TARIFF,IMPORT_TARIFF,SUNLIGHT,HUMIDITY,DAY,CHOCOLATE,GIFT_BASKET,ROSES,STRAWBERRIES,COCONUT,COCONUT_COUPON
0,0,1098.25,0.9,10.5,-5.0,2100.0000,70.000000,1,7988.0,71114.5,14545.5,4030.5,10000.0,637.5
1,100,1098.25,0.9,9.5,-5.0,2099.7570,70.022710,1,7988.0,71114.0,14543.5,4030.5,9999.5,637.5
2,200,1096.75,0.9,9.5,-5.0,2099.5132,70.045395,1,7987.5,71115.5,14543.5,4030.0,9998.5,637.5
3,300,1097.00,0.9,9.5,-5.0,2099.2683,70.068030,1,7988.5,71123.5,14541.5,4030.0,9999.5,638.5
4,400,1097.25,0.9,9.5,-5.0,2099.0225,70.090640,1,7989.5,71132.5,14547.5,4030.0,9998.5,637.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,999600,1036.25,0.9,9.5,-5.0,2299.9436,69.935490,1,7885.5,70599.5,14418.0,4036.5,10136.5,682.5
9997,999700,1036.25,0.9,9.5,-5.0,2299.9556,69.951530,1,7885.5,70585.5,14421.5,4035.5,10134.5,681.5
9998,999800,1036.25,0.9,9.5,-5.0,2299.9690,69.967620,1,7887.5,70584.5,14419.0,4035.5,10135.0,681.5
9999,999900,1034.25,0.9,9.5,-5.0,2299.9840,69.983780,1,7887.5,70586.5,14422.5,4036.0,10135.0,682.5
10000,1000000,1035.25,0.9,9.5,-5.0,2300.0000,70.000000,1,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
df.columns

Index(['timestamp', 'ORCHIDS', 'TRANSPORT_FEES', 'EXPORT_TARIFF',
       'IMPORT_TARIFF', 'SUNLIGHT', 'HUMIDITY', 'DAY', 'CHOCOLATE',
       'GIFT_BASKET', 'ROSES', 'STRAWBERRIES', 'COCONUT', 'COCONUT_COUPON'],
      dtype='object')

# helpers

In [73]:
def get_prev_returns(df, col, its):
    prev_col = f"{col}_prev_{its}_its"
    df[prev_col] = df[col].shift(its)
    df[f"{col}_returns_from_{its}_its_ago"] = (df[col] - df[prev_col]) / df[prev_col]
    df.drop(columns=[prev_col], inplace=True)
    return df

def get_future_returns(df, col, its):
    future_col = f"{col}_future_{its}_its"
    df[future_col] = df[col].shift(-its)
    df[f"{col}_returns_in_{its}_its"] = (df[future_col] - df[col]) / df[col]
    df.drop(columns=[future_col], inplace=True)
    return df

def get_centered_returns(df, col, its):
    future_col = f"{col}_future_{its}_its"
    df[future_col] = df[col].shift(-its)
    prev_col = f"{col}_prev_{its}_its"
    df[prev_col] = df[col].shift(its)
    df[f"{col}_returns_centered_with_{its}_its"] = (df[future_col] - df[prev_col])/df[prev_col]
    df.drop(columns=[prev_col], inplace=True)
    df.drop(columns=[future_col], inplace=True)
    return df

# regs

In [74]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import scipy.stats as stats

timeframes = [1, 2, 3, 5, 7, 10, 15, 25, 50, 75, 100, 150, 200, 250, 300, 350, 400, 500]
symbols = ['ORCHIDS', 'CHOCOLATE', 'GIFT_BASKET', 'ROSES', 'STRAWBERRIES', 'COCONUT', 'COCONUT_COUPON']

df_copy = df.copy()

for timeframe in timeframes:
    print(f"Timeframe: {timeframe} iterations")
    
    # Add lagged and future returns columns for each symbol
    for symbol in symbols:
        df_copy = get_prev_returns(df_copy, symbol, timeframe)
        df_copy = get_future_returns(df_copy, symbol, timeframe)
    
    for target_symbol in symbols:
        print(f"Target Symbol: {target_symbol}")
        
        # Get the feature columns (lagged returns from other symbols)
        feature_cols = [col for col in df_copy.columns if col.endswith(f"_returns_from_{timeframe}_its_ago") and not col.startswith(target_symbol)]
        
        # Get the target column (future returns for the target symbol)
        target_col = f"{target_symbol}_returns_in_{timeframe}_its"
        
        # Drop rows with missing values
        df_train = df_copy[feature_cols + [target_col]].dropna()
        
        # Split the data into features (X) and target (y)
        X = df_train[feature_cols]
        y = df_train[target_col]
        
        # Create and fit the linear regression model (without y-intercept)
        model = LinearRegression(fit_intercept=False)
        model.fit(X, y)
        
        # Print the learned equation
        equation = f"{target_col} = " + " + ".join([f"{coef:.4f} * {feat}" for feat, coef in zip(feature_cols, model.coef_)])
        print("Learned Equation:")
        print(equation)
        
        # Make predictions on the training data
        y_pred = model.predict(X)
        
        # Calculate and print the R-squared and p-value
        r2 = r2_score(y, y_pred)
        print(f"R-squared: {r2:.4f}")
        
        _, p_value = stats.pearsonr(y, y_pred)
        print(f"p-value: {p_value:.4f}")
        
        print()
    
    df_copy = df_copy[['timestamp'] + symbols]
    
    print()

Timeframe: 1 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_1_its = -0.0651 * CHOCOLATE_returns_from_1_its_ago + 0.2678 * GIFT_BASKET_returns_from_1_its_ago + -0.0265 * ROSES_returns_from_1_its_ago + 0.0613 * STRAWBERRIES_returns_from_1_its_ago + -0.0192 * COCONUT_returns_from_1_its_ago + -0.0035 * COCONUT_COUPON_returns_from_1_its_ago
R-squared: 0.0008
p-value: 0.0048

Target Symbol: CHOCOLATE
Learned Equation:
CHOCOLATE_returns_in_1_its = -0.0033 * ORCHIDS_returns_from_1_its_ago + 0.0103 * GIFT_BASKET_returns_from_1_its_ago + 0.0021 * ROSES_returns_from_1_its_ago + -0.0104 * STRAWBERRIES_returns_from_1_its_ago + 0.0062 * COCONUT_returns_from_1_its_ago + 0.0002 * COCONUT_COUPON_returns_from_1_its_ago
R-squared: 0.0008
p-value: 0.0024

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_1_its = -0.0013 * ORCHIDS_returns_from_1_its_ago + 0.0005 * CHOCOLATE_returns_from_1_its_ago + 0.0072 * ROSES_returns_from_1_its_ago + -0.0075 * STRAWBERRIES_returns_from_1_its_ago + -0.0131 * COCONUT_returns_from_1_its_ago + 0.0001 * COCONUT_COUPON_returns_from_1_its_ago
R-squared: 0.0004
p-value: 0.0308

Target Symbol: ROSES
Learned Equation:
ROSES_returns_in_1_its = 0.0008 * ORCHIDS_returns_from_1_its_ago + 0.0022 * CHOCOLATE_returns_from_1_its_ago + 0.0133 * GIFT_BASKET_returns_from_1_its_ago + -0.0322 * STRAWBERRIES_returns_from_1_its_ago + 0.0092 * COCONUT_returns_from_1_its_ago + 0.0007 * COCONUT_COUPON_returns_from_1_its_ago
R-squared: 0.0005
p-value: 0.0273

Target Symbol: STRAWBERRIES
Learned Equation:
STRAWBERRIES_returns_in_1_its = -0.0036 * ORCHIDS_returns_from_1_its_ago + 0.0221 * CHOCOLATE_returns_from_1_its_ago + -0.0105 * GIFT_BASKET_returns_from_1_its_ago + -0.0057 * ROSES_returns_from_1_its_ago + -0.0094 * COCONUT_returns_from_1_its_ago + -0.0002 * COCONUT_COUPON_returns_from_1_its_ago
R-squared: 0.0019
p-value: 0.0000

Target Symbol: COCONUT
Learned Equation:
COCONUT_returns_in_1_its = -0.0002 * ORCHIDS_returns_from_1_its_ago + -0.0195 * CHOCOLATE_returns_from_1_its_ago + 0.0118 * GIFT_BASKET_returns_from_1_its_ago + 0.0019 * ROSES_returns_from_1_its_ago + -0.0240 * STRAWBERRIES_returns_from_1_its_ago
R-squared: 0.0008
p-value: 0.0019

Target Symbol: COCONUT_COUPON
Learned Equation:
COCONUT_COUPON_returns_in_1_its = -0.0344 * ORCHIDS_returns_from_1_its_ago + -0.1712 * CHOCOLATE_returns_from_1_its_ago + 0.0792 * GIFT_BASKET_returns_from_1_its_ago + 0.1123 * ROSES_returns_from_1_its_ago + -0.2226 * STRAWBERRIES_returns_from_1_its_ago + 0.0786 * COCONUT_returns_from_1_its_ago
R-squared: 0.0008
p-value: 0.0041


Timeframe: 2 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_2_its = -0.1991 * CHOCOLATE_returns_from_2_its_ago + 0.2147 * GIFT_BASKET_returns_from_2_its_ago + -0.0472 * ROSES_returns_from_2_its_ago + -0.1575 * STRAWBERRIES_returns_from_2_its_ago + -0.1485 * COCONUT_returns_from_2_its_ago + -0.0043 * COCONUT_COUPON_returns_from_2_its_ago
R-squared: 0.0008
p-value: 0.0030

Target Symbol: CHOCOLATE
Learned Equation:
CHOCOLATE_returns_in_2_its = -0.0025 * ORCHIDS_returns_from_2_its_ago + 0.0201 * GIFT_BASKET_returns_from_2_its_ago + -0.0094 * ROSES_returns_from_2_its_ago + 0.0021 * STRAWBERRIES_returns_from_2_its_ago + -0.0165 * COCONUT_returns_from_2_its_ago + 0.0008 * COCONUT_COUPON_returns_from_2_its_ago
R-squared: 0.0007
p-value: 0.0021

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_2_its = -0.0004 * ORCHIDS_returns_from_2_its_ago + 0.0051 * CHOCOLATE_returns_from_2_its_ago + -0.0049 * ROSES_returns_from_2_its_ago + 0.0117 * STRAWBERRIES_returns_from_2_its_ago + -0.0221 * COCONUT_returns_from_2_its_ago + -0.0002 * COCONUT_COUPON_returns_from_2_its_ago
R-squared: 0.0006
p-value: 0.0087

Target Symbol: ROSES
Learned Equation:
ROSES_returns_in_2_its = 0.0025 * ORCHIDS_returns_from_2_its_ago + -0.0083 * CHOCOLATE_returns_from_2_its_ago + -0.0057 * GIFT_BASKET_returns_from_2_its_ago + 0.0259 * STRAWBERRIES_returns_from_2_its_ago + 0.0304 * COCONUT_returns_from_2_its_ago + -0.0010 * COCONUT_COUPON_returns_from_2_its_ago
R-squared: 0.0006
p-value: 0.0112

Target Symbol: STRAWBERRIES
Learned Equation:
STRAWBERRIES_returns_in_2_its = 0.0008 * ORCHIDS_returns_from_2_its_ago + 0.0179 * CHOCOLATE_returns_from_2_its_ago + -0.0070 * GIFT_BASKET_returns_from_2_its_ago + -0.0036 * ROSES_returns_from_2_its_ago + 0.0031 * COCONUT_returns_from_2_its_ago + 0.0004 * COCONUT_COUPON_returns_from_2_its_ago
R-squared: 0.0006
p-value: 0.0153

Target Symbol: COCONUT
Learned Equation:
COCONUT_returns_in_2_its = -0.0010 * ORCHIDS_returns_from_2_its_ago + 0.0118 * CHOCOLATE_returns_from_2_its_ago + -0.0069 * GIFT_BASKET_returns_from_2_its_ago + 0.0034 * ROSES_returns_from_2_its_ago + -0.0087 * STRAWBERRIES_returns_from_2_its_ago
R-squared: 0.0000
p-value: 0.0495

Target Symbol: COCONUT_COUPON
Learned Equation:
COCONUT_COUPON_returns_in_2_its = -0.0240 * ORCHIDS_returns_from_2_its_ago + -0.0322 * CHOCOLATE_returns_from_2_its_ago + 0.0630 * GIFT_BASKET_returns_from_2_its_ago + -0.0486 * ROSES_returns_from_2_its_ago + -0.3316 * STRAWBERRIES_returns_from_2_its_ago + -0.0908 * COCONUT_returns_from_2_its_ago
R-squared: 0.0005
p-value: 0.0181


Timeframe: 3 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_3_its = -0.3034 * CHOCOLATE_returns_from_3_its_ago + 0.1077 * GIFT_BASKET_returns_from_3_its_ago + 0.0223 * ROSES_returns_from_3_its_ago + 0.1126 * STRAWBERRIES_returns_from_3_its_ago + -0.1303 * COCONUT_returns_from_3_its_ago + 0.0132 * COCONUT_COUPON_returns_from_3_its_ago
R-squared: 0.0016
p-value: 0.0000

Target Symbol: CHOCOLATE
Learned Equation:
CHOCOLATE_returns_in_3_its = -0.0030 * ORCHIDS_returns_from_3_its_ago + -0.0034 * GIFT_BASKET_returns_from_3_its_ago + 0.0026 * ROSES_returns_from_3_its_ago + 0.0166 * STRAWBERRIES_returns_from_3_its_ago + -0.0398 * COCONUT_returns_from_3_its_ago + 0.0005 * COCONUT_COUPON_returns_from_3_its_ago
R-squared: 0.0014
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_3_its = -0.0013 * ORCHIDS_returns_from_3_its_ago + 0.0037 * CHOCOLATE_returns_from_3_its_ago + -0.0028 * ROSES_returns_from_3_its_ago + 0.0104 * STRAWBERRIES_returns_from_3_its_ago + -0.0331 * COCONUT_returns_from_3_its_ago + -0.0007 * COCONUT_COUPON_returns_from_3_its_ago
R-squared: 0.0015
p-value: 0.0001

Target Symbol: ROSES
Learned Equation:
ROSES_returns_in_3_its = 0.0020 * ORCHIDS_returns_from_3_its_ago + -0.0176 * CHOCOLATE_returns_from_3_its_ago + 0.0212 * GIFT_BASKET_returns_from_3_its_ago + 0.0279 * STRAWBERRIES_returns_from_3_its_ago + 0.0102 * COCONUT_returns_from_3_its_ago + -0.0003 * COCONUT_COUPON_returns_from_3_its_ago
R-squared: 0.0005
p-value: 0.0140

Target Symbol: STRAWBERRIES
Learned Equation:
STRAWBERRIES_returns_in_3_its = 0.0004 * ORCHIDS_returns_from_3_its_ago + -0.0025 * CHOCOLATE_returns_from_3_its_ago + 0.0194 * GIFT_BASKET_returns_from_3_its_ago + -0.0029 * ROSES_returns_from_3_its_ago + 0.0070 * COCONUT_returns_from_3_its_ago + -0.0003 * COCONUT_COUPON_returns_from_3_its_ago
R-squared: 0.0004
p-value: 0.0430

Target Symbol: COCONUT
Learned Equation:
COCONUT_returns_in_3_its = -0.0018 * ORCHIDS_returns_from_3_its_ago + 0.0210 * CHOCOLATE_returns_from_3_its_ago + -0.0060 * GIFT_BASKET_returns_from_3_its_ago + -0.0039 * ROSES_returns_from_3_its_ago + 0.0125 * STRAWBERRIES_returns_from_3_its_ago
R-squared: 0.0006
p-value: 0.0008

Target Symbol: COCONUT_COUPON
Learned Equation:
COCONUT_COUPON_returns_in_3_its = -0.0217 * ORCHIDS_returns_from_3_its_ago + -0.0216 * CHOCOLATE_returns_from_3_its_ago + 0.1318 * GIFT_BASKET_returns_from_3_its_ago + 0.0287 * ROSES_returns_from_3_its_ago + -0.1487 * STRAWBERRIES_returns_from_3_its_ago + -0.1361 * COCONUT_returns_from_3_its_ago
R-squared: 0.0003
p-value: 0.0660


Timeframe: 5 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_5_its = -0.5075 * CHOCOLATE_returns_from_5_its_ago + 0.2146 * GIFT_BASKET_returns_from_5_its_ago + 0.0313 * ROSES_returns_from_5_its_ago + 0.2625 * STRAWBERRIES_returns_from_5_its_ago + 0.1612 * COCONUT_returns_from_5_its_ago + 0.0218 * COCONUT_COUPON_returns_from_5_its_ago
R-squared: 0.0057
p-value: 0.0000

Target Symbol: CHOCOLATE
Learned Equation:
CHOCOLATE_returns_in_5_its = -0.0022 * ORCHIDS_returns_from_5_its_ago + 0.0057 * GIFT_BASKET_returns_from_5_its_ago + -0.0093 * ROSES_returns_from_5_its_ago + 0.0245 * STRAWBERRIES_returns_from_5_its_ago + -0.0536 * COCONUT_returns_from_5_its_ago + 0.0020 * COCONUT_COUPON_returns_from_5_its_ago
R-squared: 0.0019
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_5_its = -0.0029 * ORCHIDS_returns_from_5_its_ago + 0.0079 * CHOCOLATE_returns_from_5_its_ago + 0.0024 * ROSES_returns_from_5_its_ago + 0.0132 * STRAWBERRIES_returns_from_5_its_ago + -0.0343 * COCONUT_returns_from_5_its_ago + -0.0006 * COCONUT_COUPON_returns_from_5_its_ago
R-squared: 0.0022
p-value: 0.0000

Target Symbol: ROSES
Learned Equation:
ROSES_returns_in_5_its = 0.0002 * ORCHIDS_returns_from_5_its_ago + 0.0103 * CHOCOLATE_returns_from_5_its_ago + 0.0269 * GIFT_BASKET_returns_from_5_its_ago + 0.0258 * STRAWBERRIES_returns_from_5_its_ago + 0.0132 * COCONUT_returns_from_5_its_ago + -0.0001 * COCONUT_COUPON_returns_from_5_its_ago
R-squared: 0.0007
p-value: 0.0054

Target Symbol: STRAWBERRIES
Learned Equation:
STRAWBERRIES_returns_in_5_its = -0.0004 * ORCHIDS_returns_from_5_its_ago + -0.0023 * CHOCOLATE_returns_from_5_its_ago + 0.0346 * GIFT_BASKET_returns_from_5_its_ago + -0.0008 * ROSES_returns_from_5_its_ago + 0.0206 * COCONUT_returns_from_5_its_ago + -0.0001 * COCONUT_COUPON_returns_from_5_its_ago
R-squared: 0.0018
p-value: 0.0000

Target Symbol: COCONUT
Learned Equation:
COCONUT_returns_in_5_its = 0.0013 * ORCHIDS_returns_from_5_its_ago + 0.0238 * CHOCOLATE_returns_from_5_its_ago + -0.0066 * GIFT_BASKET_returns_from_5_its_ago + -0.0013 * ROSES_returns_from_5_its_ago + -0.0024 * STRAWBERRIES_returns_from_5_its_ago
R-squared: -0.0000
p-value: 0.0020

Target Symbol: COCONUT_COUPON
Learned Equation:
COCONUT_COUPON_returns_in_5_its = -0.0115 * ORCHIDS_returns_from_5_its_ago + 0.1424 * CHOCOLATE_returns_from_5_its_ago + 0.0746 * GIFT_BASKET_returns_from_5_its_ago + 0.1093 * ROSES_returns_from_5_its_ago + -0.3409 * STRAWBERRIES_returns_from_5_its_ago + -0.0150 * COCONUT_returns_from_5_its_ago
R-squared: 0.0006
p-value: 0.0075


Timeframe: 7 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_7_its = -0.4255 * CHOCOLATE_returns_from_7_its_ago + -0.0978 * GIFT_BASKET_returns_from_7_its_ago + 0.0102 * ROSES_returns_from_7_its_ago + 0.3978 * STRAWBERRIES_returns_from_7_its_ago + 0.3797 * COCONUT_returns_from_7_its_ago + 0.0022 * COCONUT_COUPON_returns_from_7_its_ago
R-squared: 0.0056
p-value: 0.0000

Target Symbol: CHOCOLATE
Learned Equation:
CHOCOLATE_returns_in_7_its = -0.0012 * ORCHIDS_returns_from_7_its_ago + 0.0121 * GIFT_BASKET_returns_from_7_its_ago + -0.0162 * ROSES_returns_from_7_its_ago + 0.0298 * STRAWBERRIES_returns_from_7_its_ago + -0.0347 * COCONUT_returns_from_7_its_ago + -0.0003 * COCONUT_COUPON_returns_from_7_its_ago
R-squared: 0.0015
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_7_its = -0.0005 * ORCHIDS_returns_from_7_its_ago + 0.0016 * CHOCOLATE_returns_from_7_its_ago + 0.0122 * ROSES_returns_from_7_its_ago + 0.0220 * STRAWBERRIES_returns_from_7_its_ago + 0.0010 * COCONUT_returns_from_7_its_ago + -0.0032 * COCONUT_COUPON_returns_from_7_its_ago
R-squared: 0.0030
p-value: 0.0000

Target Symbol: ROSES
Learned Equation:
ROSES_returns_in_7_its = 0.0035 * ORCHIDS_returns_from_7_its_ago + 0.0477 * CHOCOLATE_returns_from_7_its_ago + 0.0029 * GIFT_BASKET_returns_from_7_its_ago + 0.0255 * STRAWBERRIES_returns_from_7_its_ago + 0.0781 * COCONUT_returns_from_7_its_ago + -0.0038 * COCONUT_COUPON_returns_from_7_its_ago
R-squared: 0.0031
p-value: 0.0000

Target Symbol: STRAWBERRIES
Learned Equation:
STRAWBERRIES_returns_in_7_its = 0.0005 * ORCHIDS_returns_from_7_its_ago + -0.0083 * CHOCOLATE_returns_from_7_its_ago + 0.0414 * GIFT_BASKET_returns_from_7_its_ago + 0.0030 * ROSES_returns_from_7_its_ago + 0.0207 * COCONUT_returns_from_7_its_ago + -0.0010 * COCONUT_COUPON_returns_from_7_its_ago
R-squared: 0.0024
p-value: 0.0000

Target Symbol: COCONUT

Learned Equation:
COCONUT_returns_in_7_its = 0.0027 * ORCHIDS_returns_from_7_its_ago + 0.0236 * CHOCOLATE_returns_from_7_its_ago + -0.0157 * GIFT_BASKET_returns_from_7_its_ago + 0.0022 * ROSES_returns_from_7_its_ago + -0.0189 * STRAWBERRIES_returns_from_7_its_ago
R-squared: 0.0006
p-value: 0.0000

Target Symbol: COCONUT_COUPON
Learned Equation:
COCONUT_COUPON_returns_in_7_its = -0.0260 * ORCHIDS_returns_from_7_its_ago + 0.3270 * CHOCOLATE_returns_from_7_its_ago + 0.1271 * GIFT_BASKET_returns_from_7_its_ago + 0.1652 * ROSES_returns_from_7_its_ago + -0.4347 * STRAWBERRIES_returns_from_7_its_ago + 0.2501 * COCONUT_returns_from_7_its_ago
R-squared: 0.0020
p-value: 0.0000


Timeframe: 10 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_10_its = -0.2114 * CHOCOLATE_returns_from_10_its_ago + -0.3567 * GIFT_BASKET_returns_from_10_its_ago + 0.0239 * ROSES_returns_from_10_its_ago + 0.3318 * STRAWBERRIES_returns_from_10_its_ago + 0.5273 * COCONUT_returns_from_10_its_ago + -0.0215 * COCONUT_COUPON_returns_from_10_its_ago
R-squared: 0.0050
p-value: 0.0000

Target Symbol: CHOCOLATE
Learned Equation:
CHOCOLATE_returns_in_10_its = -0.0028 * ORCHIDS_returns_from_10_its_ago + -0.0028 * GIFT_BASKET_returns_from_10_its_ago + -0.0239 * ROSES_returns_from_10_its_ago + 0.0489 * STRAWBERRIES_returns_from_10_its_ago + -0.0130 * COCONUT_returns_from_10_its_ago + -0.0035 * COCONUT_COUPON_returns_from_10_its_ago
R-squared: 0.0053
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_10_its = -0.0002 * ORCHIDS_returns_from_10_its_ago + -0.0023 * CHOCOLATE_returns_from_10_its_ago + 0.0123 * ROSES_returns_from_10_its_ago + 0.0251 * STRAWBERRIES_returns_from_10_its_ago + 0.0209 * COCONUT_returns_from_10_its_ago + -0.0043 * COCONUT_COUPON_returns_from_10_its_ago
R-squared: 0.0041
p-value: 0.0000

Target Symbol: ROSES
Learned Equation:
ROSES_returns_in_10_its = 0.0070 * ORCHIDS_returns_from_10_its_ago + 0.0783 * CHOCOLATE_returns_from_10_its_ago + -0.0121 * GIFT_BASKET_returns_from_10_its_ago + 0.0322 * STRAWBERRIES_returns_from_10_its_ago + 0.1335 * COCONUT_returns_from_10_its_ago + -0.0058 * COCONUT_COUPON_returns_from_10_its_ago
R-squared: 0.0082
p-value: 0.0000

Target Symbol: STRAWBERRIES
Learned Equation:
STRAWBERRIES_returns_in_10_its = 0.0026 * ORCHIDS_returns_from_10_its_ago + -0.0145 * CHOCOLATE_returns_from_10_its_ago + 0.0469 * GIFT_BASKET_returns_from_10_its_ago + 0.0161 * ROSES_returns_from_10_its_ago + 0.0034 * COCONUT_returns_from_10_its_ago + -0.0009 * COCONUT_COUPON_returns_from_10_its_ago
R-squared: 0.0054
p-value: 0.0000

Target Symbol: COCONUT
Learned Equation:
COCONUT_returns_in_10_its = 0.0013 * ORCHIDS_returns_from_10_its_ago + 0.0160 * CHOCOLATE_returns_from_10_its_ago + -0.0142 * GIFT_BASKET_returns_from_10_its_ago + 0.0055 * ROSES_returns_from_10_its_ago + -0.0210 * STRAWBERRIES_returns_from_10_its_ago
R-squared: -0.0007
p-value: 0.0010

Target Symbol: COCONUT_COUPON
Learned Equation:
COCONUT_COUPON_returns_in_10_its = -0.0402 * ORCHIDS_returns_from_10_its_ago + 0.3251 * CHOCOLATE_returns_from_10_its_ago + 0.2291 * GIFT_BASKET_returns_from_10_its_ago + 0.1470 * ROSES_returns_from_10_its_ago + 0.1668 * STRAWBERRIES_returns_from_10_its_ago + -0.0402 * COCONUT_returns_from_10_its_ago
R-squared: 0.0021
p-value: 0.0000


Timeframe: 15 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_15_its = -0.1790 * CHOCOLATE_returns_from_15_its_ago + -0.1935 * GIFT_BASKET_returns_from_15_its_ago + -0.0366 * ROSES_returns_from_15_its_ago + 0.1985 * STRAWBERRIES_returns_from_15_its_ago + 0.7262 * COCONUT_returns_from_15_its_ago + -0.0332 * COCONUT_COUPON_returns_from_15_its_ago
R-squared: 0.0052
p-value: 0.0000

Target Symbol: CHOCOLATE
Learned Equation:
CHOCOLATE_returns_in_15_its = -0.0012 * ORCHIDS_returns_from_15_its_ago + -0.0237 * GIFT_BASKET_returns_from_15_its_ago + -0.0038 * ROSES_returns_from_15_its_ago + 0.0620 * STRAWBERRIES_returns_from_15_its_ago + -0.0678 * COCONUT_returns_from_15_its_ago + -0.0012 * COCONUT_COUPON_returns_from_15_its_ago
R-squared: 0.0051
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_15_its = -0.0013 * ORCHIDS_returns_from_15_its_ago + -0.0102 * CHOCOLATE_returns_from_15_its_ago + 0.0055 * ROSES_returns_from_15_its_ago + -0.0006 * STRAWBERRIES_returns_from_15_its_ago + -0.0459 * COCONUT_returns_from_15_its_ago + 0.0004 * COCONUT_COUPON_returns_from_15_its_ago
R-squared: 0.0011
p-value: 0.0000

Target Symbol: ROSES
Learned Equation:
ROSES_returns_in_15_its = 0.0024 * ORCHIDS_returns_from_15_its_ago + 0.0318 * CHOCOLATE_returns_from_15_its_ago + 0.0085 * GIFT_BASKET_returns_from_15_its_ago + 0.0215 * STRAWBERRIES_returns_from_15_its_ago + 0.0870 * COCONUT_returns_from_15_its_ago + -0.0040 * COCONUT_COUPON_returns_from_15_its_ago
R-squared: 0.0024
p-value: 0.0000

Target Symbol: STRAWBERRIES
Learned Equation:
STRAWBERRIES_returns_in_15_its = 0.0010 * ORCHIDS_returns_from_15_its_ago + -0.0244 * CHOCOLATE_returns_from_15_its_ago + 0.0393 * GIFT_BASKET_returns_from_15_its_ago + 0.0258 * ROSES_returns_from_15_its_ago + -0.0317 * COCONUT_returns_from_15_its_ago + 0.0009 * COCONUT_COUPON_returns_from_15_its_ago
R-squared: 0.0066
p-value: 0.0000

Target Symbol: COCONUT
Learned Equation:
COCONUT_returns_in_15_its = -0.0006 * ORCHIDS_returns_from_15_its_ago + -0.0171 * CHOCOLATE_returns_from_15_its_ago + -0.0129 * GIFT_BASKET_returns_from_15_its_ago + 0.0087 * ROSES_returns_from_15_its_ago + -0.0208 * STRAWBERRIES_returns_from_15_its_ago
R-squared: -0.0009
p-value: 0.0001

Target Symbol: COCONUT_COUPON
Learned Equation:
COCONUT_COUPON_returns_in_15_its = -0.0527 * ORCHIDS_returns_from_15_its_ago + 0.4051 * CHOCOLATE_returns_from_15_its_ago + -0.6489 * GIFT_BASKET_returns_from_15_its_ago + 0.3128 * ROSES_returns_from_15_its_ago + 0.7446 * STRAWBERRIES_returns_from_15_its_ago + -0.6475 * COCONUT_returns_from_15_its_ago
R-squared: 0.0043
p-value: 0.0000


Timeframe: 25 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_25_its = -0.1705 * CHOCOLATE_returns_from_25_its_ago + 0.2556 * GIFT_BASKET_returns_from_25_its_ago + 0.0040 * ROSES_returns_from_25_its_ago + 0.4249 * STRAWBERRIES_returns_from_25_its_ago + 0.3046 * COCONUT_returns_from_25_its_ago + -0.0228 * COCONUT_COUPON_returns_from_25_its_ago
R-squared: 0.0032
p-value: 0.0000

Target Symbol: CHOCOLATE
Learned Equation:
CHOCOLATE_returns_in_25_its = 0.0015 * ORCHIDS_returns_from_25_its_ago + -0.0280 * GIFT_BASKET_returns_from_25_its_ago + 0.0259 * ROSES_returns_from_25_its_ago + 0.0208 * STRAWBERRIES_returns_from_25_its_ago + -0.1822 * COCONUT_returns_from_25_its_ago + 0.0025 * COCONUT_COUPON_returns_from_25_its_ago
R-squared: 0.0172
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_25_its = -0.0011 * ORCHIDS_returns_from_25_its_ago + 0.0372 * CHOCOLATE_returns_from_25_its_ago + -0.0045 * ROSES_returns_from_25_its_ago + -0.0431 * STRAWBERRIES_returns_from_25_its_ago + -0.1327 * COCONUT_returns_from_25_its_ago + 0.0033 * COCONUT_COUPON_returns_from_25_its_ago
R-squared: 0.0134
p-value: 0.0000

Target Symbol: ROSES
Learned Equation:
ROSES_returns_in_25_its = -0.0064 * ORCHIDS_returns_from_25_its_ago + 0.0032 * CHOCOLATE_returns_from_25_its_ago + 0.0221 * GIFT_BASKET_returns_from_25_its_ago + -0.0582 * STRAWBERRIES_returns_from_25_its_ago + 0.0239 * COCONUT_returns_from_25_its_ago + -0.0084 * COCONUT_COUPON_returns_from_25_its_ago
R-squared: 0.0063
p-value: 0.0000

Target Symbol: STRAWBERRIES
Learned Equation:
STRAWBERRIES_returns_in_25_its = -0.0015 * ORCHIDS_returns_from_25_its_ago + 0.0002 * CHOCOLATE_returns_from_25_its_ago + 0.0121 * GIFT_BASKET_returns_from_25_its_ago + 0.0232 * ROSES_returns_from_25_its_ago + -0.0224 * COCONUT_returns_from_25_its_ago + 0.0016 * COCONUT_COUPON_returns_from_25_its_ago
R-squared: 0.0037
p-value: 0.0000

Target Symbol: COCONUT
Learned Equation:
COCONUT_returns_in_25_its = -0.0030 * ORCHIDS_returns_from_25_its_ago + -0.0182 * CHOCOLATE_returns_from_25_its_ago + -0.0061 * GIFT_BASKET_returns_from_25_its_ago + 0.0450 * ROSES_returns_from_25_its_ago + -0.0339 * STRAWBERRIES_returns_from_25_its_ago
R-squared: 0.0045
p-value: 0.0000

Target Symbol: COCONUT_COUPON
Learned Equation:
COCONUT_COUPON_returns_in_25_its = 0.0107 * ORCHIDS_returns_from_25_its_ago + 0.4452 * CHOCOLATE_returns_from_25_its_ago + -0.7769 * GIFT_BASKET_returns_from_25_its_ago + 0.4323 * ROSES_returns_from_25_its_ago + 0.5345 * STRAWBERRIES_returns_from_25_its_ago + -0.5426 * COCONUT_returns_from_25_its_ago
R-squared: 0.0028
p-value: 0.0000


Timeframe: 50 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_50_its = -0.4255 * CHOCOLATE_returns_from_50_its_ago + -0.4214 * GIFT_BASKET_returns_from_50_its_ago + 0.2344 * ROSES_returns_from_50_its_ago + 0.9606 * STRAWBERRIES_returns_from_50_its_ago + -0.1277 * COCONUT_returns_from_50_its_ago + -0.0525 * COCONUT_COUPON_returns_from_50_its_ago
R-squared: 0.0172
p-value: 0.0000

Target Symbol: CHOCOLATE
Learned Equation:
CHOCOLATE_returns_in_50_its = -0.0037 * ORCHIDS_returns_from_50_its_ago + -0.0090 * GIFT_BASKET_returns_from_50_its_ago + 0.0029 * ROSES_returns_from_50_its_ago + 0.0426 * STRAWBERRIES_returns_from_50_its_ago + -0.0667 * COCONUT_returns_from_50_its_ago + 0.0014 * COCONUT_COUPON_returns_from_50_its_ago
R-squared: -0.0017
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_50_its = -0.0004 * ORCHIDS_returns_from_50_its_ago + 0.0454 * CHOCOLATE_returns_from_50_its_ago + -0.0159 * ROSES_returns_from_50_its_ago + -0.0084 * STRAWBERRIES_returns_from_50_its_ago + 0.0313 * COCONUT_returns_from_50_its_ago + 0.0054 * COCONUT_COUPON_returns_from_50_its_ago
R-squared: 0.0102
p-value: 0.0000

Target Symbol: ROSES

Learned Equation:
ROSES_returns_in_50_its = -0.0068 * ORCHIDS_returns_from_50_its_ago + 0.1264 * CHOCOLATE_returns_from_50_its_ago + -0.1277 * GIFT_BASKET_returns_from_50_its_ago + -0.1745 * STRAWBERRIES_returns_from_50_its_ago + 0.1060 * COCONUT_returns_from_50_its_ago + -0.0088 * COCONUT_COUPON_returns_from_50_its_ago
R-squared: 0.0221
p-value: 0.0000

Target Symbol: STRAWBERRIES
Learned Equation:
STRAWBERRIES_returns_in_50_its = -0.0043 * ORCHIDS_returns_from_50_its_ago + 0.0523 * CHOCOLATE_returns_from_50_its_ago + -0.0114 * GIFT_BASKET_returns_from_50_its_ago + -0.0235 * ROSES_returns_from_50_its_ago + 0.0850 * COCONUT_returns_from_50_its_ago + 0.0016 * COCONUT_COUPON_returns_from_50_its_ago
R-squared: 0.0181
p-value: 0.0000

Target Symbol: COCONUT
Learned Equation:
COCONUT_returns_in_50_its = 0.0053 * ORCHIDS_returns_from_50_its_ago + 0.0858 * CHOCOLATE_returns_from_50_its_ago + -0.1541 * GIFT_BASKET_returns_from_50_its_ago + 0.0594 * ROSES_returns_from_50_its_ago + 0.0202 * STRAWBERRIES_returns_from_50_its_ago
R-squared: 0.0119
p-value: 0.0000

Target Symbol: COCONUT_COUPON
Learned Equation:
COCONUT_COUPON_returns_in_50_its = 0.0897 * ORCHIDS_returns_from_50_its_ago + 0.9887 * CHOCOLATE_returns_from_50_its_ago + -1.7592 * GIFT_BASKET_returns_from_50_its_ago + -0.2888 * ROSES_returns_from_50_its_ago + 0.2266 * STRAWBERRIES_returns_from_50_its_ago + 0.6145 * COCONUT_returns_from_50_its_ago
R-squared: 0.0156
p-value: 0.0000


Timeframe: 75 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_75_its = 0.2477 * CHOCOLATE_returns_from_75_its_ago + -1.1073 * GIFT_BASKET_returns_from_75_its_ago + 0.4499 * ROSES_returns_from_75_its_ago + 0.3721 * STRAWBERRIES_returns_from_75_its_ago + 0.4797 * COCONUT_returns_from_75_its_ago + -0.0644 * COCONUT_COUPON_returns_from_75_its_ago
R-squared: 0.0161
p-value: 0.0000

Target Symbol: CHOCOLATE
Learned Equation:
CHOCOLATE_returns_in_75_its = -0.0026 * ORCHIDS_returns_from_75_its_ago + 0.0242 * GIFT_BASKET_returns_from_75_its_ago + 0.0236 * ROSES_returns_from_75_its_ago + -0.0734 * STRAWBERRIES_returns_from_75_its_ago + -0.1013 * COCONUT_returns_from_75_its_ago + 0.0057 * COCONUT_COUPON_returns_from_75_its_ago
R-squared: 0.0016
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_75_its = 0.0041 * ORCHIDS_returns_from_75_its_ago + 0.0327 * CHOCOLATE_returns_from_75_its_ago + 0.0308 * ROSES_returns_from_75_its_ago + -0.0672 * STRAWBERRIES_returns_from_75_its_ago + -0.0349 * COCONUT_returns_from_75_its_ago + 0.0116 * COCONUT_COUPON_returns_from_75_its_ago
R-squared: 0.0293
p-value: 0.0000

Target Symbol: ROSES
Learned Equation:
ROSES_returns_in_75_its = 0.0090 * ORCHIDS_returns_from_75_its_ago + 0.1233 * CHOCOLATE_returns_from_75_its_ago + -0.0666 * GIFT_BASKET_returns_from_75_its_ago + -0.1736 * STRAWBERRIES_returns_from_75_its_ago + -0.0865 * COCONUT_returns_from_75_its_ago + 0.0033 * COCONUT_COUPON_returns_from_75_its_ago
R-squared: 0.0142
p-value: 0.0000

Target Symbol: STRAWBERRIES
Learned Equation:
STRAWBERRIES_returns_in_75_its = 0.0018 * ORCHIDS_returns_from_75_its_ago + 0.0946 * CHOCOLATE_returns_from_75_its_ago + -0.0173 * GIFT_BASKET_returns_from_75_its_ago + -0.0201 * ROSES_returns_from_75_its_ago + 0.1612 * COCONUT_returns_from_75_its_ago + 0.0006 * COCONUT_COUPON_returns_from_75_its_ago
R-squared: 0.0398
p-value: 0.0000

Target Symbol: COCONUT
Learned Equation:
COCONUT_returns_in_75_its = 0.0070 * ORCHIDS_returns_from_75_its_ago + 0.1490 * CHOCOLATE_returns_from_75_its_ago + -0.1915 * GIFT_BASKET_returns_from_75_its_ago + 0.0709 * ROSES_returns_from_75_its_ago + 0.0364 * STRAWBERRIES_returns_from_75_its_ago
R-squared: 0.0204
p-value: 0.0000

Target Symbol: COCONUT_COUPON
Learned Equation:
COCONUT_COUPON_returns_in_75_its = 0.0584 * ORCHIDS_returns_from_75_its_ago + 1.9871 * CHOCOLATE_returns_from_75_its_ago + -0.7566 * GIFT_BASKET_returns_from_75_its_ago + 0.0239 * ROSES_returns_from_75_its_ago + -1.0931 * STRAWBERRIES_returns_from_75_its_ago + 0.4006 * COCONUT_returns_from_75_its_ago
R-squared: 0.0173
p-value: 0.0000


Timeframe: 100 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_100_its = 0.8901 * CHOCOLATE_returns_from_100_its_ago + -1.3315 * GIFT_BASKET_returns_from_100_its_ago + 0.3869 * ROSES_returns_from_100_its_ago + -0.0255 * STRAWBERRIES_returns_from_100_its_ago + 0.3438 * COCONUT_returns_from_100_its_ago + -0.0287 * COCONUT_COUPON_returns_from_100_its_ago
R-squared: 0.0117
p-value: 0.0000

Target Symbol: CHOCOLATE
Learned Equation:
CHOCOLATE_returns_in_100_its = 0.0025 * ORCHIDS_returns_from_100_its_ago + -0.0083 * GIFT_BASKET_returns_from_100_its_ago + 0.0343 * ROSES_returns_from_100_its_ago + -0.1509 * STRAWBERRIES_returns_from_100_its_ago + -0.1564 * COCONUT_returns_from_100_its_ago + 0.0084 * COCONUT_COUPON_returns_from_100_its_ago
R-squared: 0.0156
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_100_its = 0.0099 * ORCHIDS_returns_from_100_its_ago + 0.0361 * CHOCOLATE_returns_from_100_its_ago + 0.0353 * ROSES_returns_from_100_its_ago + -0.1613 * STRAWBERRIES_returns_from_100_its_ago + -0.0775 * COCONUT_returns_from_100_its_ago + 0.0118 * COCONUT_COUPON_returns_from_100_its_ago
R-squared: 0.0435
p-value: 0.0000

Target Symbol: ROSES
Learned Equation:
ROSES_returns_in_100_its = 0.0124 * ORCHIDS_returns_from_100_its_ago + 0.1350 * CHOCOLATE_returns_from_100_its_ago + -0.0583 * GIFT_BASKET_returns_from_100_its_ago + -0.1057 * STRAWBERRIES_returns_from_100_its_ago + -0.3260 * COCONUT_returns_from_100_its_ago + 0.0059 * COCONUT_COUPON_returns_from_100_its_ago
R-squared: 0.0355
p-value: 0.0000

Target Symbol: STRAWBERRIES
Learned Equation:
STRAWBERRIES_returns_in_100_its = 0.0031 * ORCHIDS_returns_from_100_its_ago + 0.0713 * CHOCOLATE_returns_from_100_its_ago + -0.0257 * GIFT_BASKET_returns_from_100_its_ago + -0.0137 * ROSES_returns_from_100_its_ago + 0.1392 * COCONUT_returns_from_100_its_ago + 0.0037 * COCONUT_COUPON_returns_from_100_its_ago
R-squared: 0.0426
p-value: 0.0000

Target Symbol: COCONUT
Learned Equation:
COCONUT_returns_in_100_its = 0.0028 * ORCHIDS_returns_from_100_its_ago + 0.2415 * CHOCOLATE_returns_from_100_its_ago + -0.2328 * GIFT_BASKET_returns_from_100_its_ago + 0.0843 * ROSES_returns_from_100_its_ago + 0.0251 * STRAWBERRIES_returns_from_100_its_ago
R-squared: 0.0367
p-value: 0.0000

Target Symbol: COCONUT_COUPON
Learned Equation:
COCONUT_COUPON_returns_in_100_its = 0.0364 * ORCHIDS_returns_from_100_its_ago + 3.1005 * CHOCOLATE_returns_from_100_its_ago + -0.7769 * GIFT_BASKET_returns_from_100_its_ago + 0.3302 * ROSES_returns_from_100_its_ago + -1.5069 * STRAWBERRIES_returns_from_100_its_ago + -1.0994 * COCONUT_returns_from_100_its_ago
R-squared: 0.0486
p-value: 0.0000


Timeframe: 150 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_150_its = 1.5070 * CHOCOLATE_returns_from_150_its_ago + -1.7847 * GIFT_BASKET_returns_from_150_its_ago + -0.1368 * ROSES_returns_from_150_its_ago + 0.0394 * STRAWBERRIES_returns_from_150_its_ago + -0.6066 * COCONUT_returns_from_150_its_ago + 0.0544 * COCONUT_COUPON_returns_from_150_its_ago
R-squared: 0.0295
p-value: 0.0000

Target Symbol: CHOCOLATE
Learned Equation:
CHOCOLATE_returns_in_150_its = -0.0071 * ORCHIDS_returns_from_150_its_ago + -0.0991 * GIFT_BASKET_returns_from_150_its_ago + -0.0320 * ROSES_returns_from_150_its_ago + -0.0947 * STRAWBERRIES_returns_from_150_its_ago + -0.2155 * COCONUT_returns_from_150_its_ago + 0.0117 * COCONUT_COUPON_returns_from_150_its_ago
R-squared: 0.0392
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_150_its = 0.0057 * ORCHIDS_returns_from_150_its_ago + 0.0414 * CHOCOLATE_returns_from_150_its_ago + 0.0142 * ROSES_returns_from_150_its_ago + -0.1245 * STRAWBERRIES_returns_from_150_its_ago + -0.1448 * COCONUT_returns_from_150_its_ago + 0.0083 * COCONUT_COUPON_returns_from_150_its_ago
R-squared: 0.0234
p-value: 0.0000

Target Symbol: ROSES
Learned Equation:
ROSES_returns_in_150_its = 0.0080 * ORCHIDS_returns_from_150_its_ago + 0.2416 * CHOCOLATE_returns_from_150_its_ago + -0.0289 * GIFT_BASKET_returns_from_150_its_ago + -0.0391 * STRAWBERRIES_returns_from_150_its_ago + -0.4740 * COCONUT_returns_from_150_its_ago + 0.0128 * COCONUT_COUPON_returns_from_150_its_ago
R-squared: 0.0772
p-value: 0.0000

Target Symbol: STRAWBERRIES
Learned Equation:
STRAWBERRIES_returns_in_150_its = 0.0001 * ORCHIDS_returns_from_150_its_ago + 0.0482 * CHOCOLATE_returns_from_150_its_ago + -0.0878 * GIFT_BASKET_returns_from_150_its_ago + 0.0114 * ROSES_returns_from_150_its_ago + -0.0273 * COCONUT_returns_from_150_its_ago + 0.0080 * COCONUT_COUPON_returns_from_150_its_ago
R-squared: 0.0207
p-value: 0.0000

Target Symbol: COCONUT
Learned Equation:
COCONUT_returns_in_150_its = -0.0015 * ORCHIDS_returns_from_150_its_ago + 0.2642 * CHOCOLATE_returns_from_150_its_ago + -0.2062 * GIFT_BASKET_returns_from_150_its_ago + 0.1342 * ROSES_returns_from_150_its_ago + -0.0349 * STRAWBERRIES_returns_from_150_its_ago
R-squared: 0.0689
p-value: 0.0000

Target Symbol: COCONUT_COUPON
Learned Equation:
COCONUT_COUPON_returns_in_150_its = -0.0859 * ORCHIDS_returns_from_150_its_ago + 2.3710 * CHOCOLATE_returns_from_150_its_ago + -0.6039 * GIFT_BASKET_returns_from_150_its_ago + 1.6769 * ROSES_returns_from_150_its_ago + -0.4366 * STRAWBERRIES_returns_from_150_its_ago + -2.2621 * COCONUT_returns_from_150_its_ago
R-squared: 0.0877
p-value: 0.0000


Timeframe: 200 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_200_its = 2.3069 * CHOCOLATE_returns_from_200_its_ago + -2.1396 * GIFT_BASKET_returns_from_200_its_ago + -0.7135 * ROSES_returns_from_200_its_ago + -0.3829 * STRAWBERRIES_returns_from_200_its_ago + -1.3542 * COCONUT_returns_from_200_its_ago + 0.0422 * COCONUT_COUPON_returns_from_200_its_ago
R-squared: 0.0902
p-value: 0.0000

Target Symbol: CHOCOLATE

Learned Equation:
CHOCOLATE_returns_in_200_its = -0.0067 * ORCHIDS_returns_from_200_its_ago + -0.1333 * GIFT_BASKET_returns_from_200_its_ago + -0.0782 * ROSES_returns_from_200_its_ago + -0.0879 * STRAWBERRIES_returns_from_200_its_ago + -0.2559 * COCONUT_returns_from_200_its_ago + 0.0230 * COCONUT_COUPON_returns_from_200_its_ago
R-squared: 0.1006
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_200_its = -0.0017 * ORCHIDS_returns_from_200_its_ago + 0.0399 * CHOCOLATE_returns_from_200_its_ago + -0.0014 * ROSES_returns_from_200_its_ago + -0.0469 * STRAWBERRIES_returns_from_200_its_ago + -0.1721 * COCONUT_returns_from_200_its_ago + 0.0126 * COCONUT_COUPON_returns_from_200_its_ago
R-squared: 0.0264
p-value: 0.0000

Target Symbol: ROSES
Learned Equation:
ROSES_returns_in_200_its = 0.0020 * ORCHIDS_returns_from_200_its_ago + 0.3393 * CHOCOLATE_returns_from_200_its_ago + 0.1018 * GIFT_BASKET_returns_from_200_its_ago + -0.0526 * STRAWBERRIES_returns_from_200_its_ago + -0.4948 * COCONUT_returns_from_200_its_ago + 0.0185 * COCONUT_COUPON_returns_from_200_its_ago
R-squared: 0.1364
p-value: 0.0000

Target Symbol: STRAWBERRIES
Learned Equation:
STRAWBERRIES_returns_in_200_its = -0.0062 * ORCHIDS_returns_from_200_its_ago + 0.0669 * CHOCOLATE_returns_from_200_its_ago + -0.0774 * GIFT_BASKET_returns_from_200_its_ago + 0.0128 * ROSES_returns_from_200_its_ago + 0.0359 * COCONUT_returns_from_200_its_ago + 0.0015 * COCONUT_COUPON_returns_from_200_its_ago
R-squared: 0.0147
p-value: 0.0000

Target Symbol: COCONUT
Learned Equation:
COCONUT_returns_in_200_its = -0.0064 * ORCHIDS_returns_from_200_its_ago + 0.2176 * CHOCOLATE_returns_from_200_its_ago + -0.0801 * GIFT_BASKET_returns_from_200_its_ago + 0.1507 * ROSES_returns_from_200_its_ago + -0.0826 * STRAWBERRIES_returns_from_200_its_ago
R-squared: 0.0890
p-value: 0.0000

Target Symbol: COCONUT_COUPON
Learned Equation:
COCONUT_COUPON_returns_in_200_its = -0.0883 * ORCHIDS_returns_from_200_its_ago + 1.5406 * CHOCOLATE_returns_from_200_its_ago + -0.5354 * GIFT_BASKET_returns_from_200_its_ago + 2.6100 * ROSES_returns_from_200_its_ago + -0.2550 * STRAWBERRIES_returns_from_200_its_ago + -1.6921 * COCONUT_returns_from_200_its_ago
R-squared: 0.1219
p-value: 0.0000


Timeframe: 250 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_250_its = 2.4239 * CHOCOLATE_returns_from_250_its_ago + -2.4411 * GIFT_BASKET_returns_from_250_its_ago + -0.8520 * ROSES_returns_from_250_its_ago + -0.5924 * STRAWBERRIES_returns_from_250_its_ago + -1.8588 * COCONUT_returns_from_250_its_ago + 0.0323 * COCONUT_COUPON_returns_from_250_its_ago
R-squared: 0.1290
p-value: 0.0000

Target Symbol: CHOCOLATE
Learned Equation:
CHOCOLATE_returns_in_250_its = 0.0030 * ORCHIDS_returns_from_250_its_ago + -0.1073 * GIFT_BASKET_returns_from_250_its_ago + -0.0883 * ROSES_returns_from_250_its_ago + -0.1121 * STRAWBERRIES_returns_from_250_its_ago + -0.2351 * COCONUT_returns_from_250_its_ago + 0.0260 * COCONUT_COUPON_returns_from_250_its_ago
R-squared: 0.0918
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_250_its = 0.0005 * ORCHIDS_returns_from_250_its_ago + 0.0716 * CHOCOLATE_returns_from_250_its_ago + -0.0252 * ROSES_returns_from_250_its_ago + -0.0362 * STRAWBERRIES_returns_from_250_its_ago + -0.1171 * COCONUT_returns_from_250_its_ago + 0.0160 * COCONUT_COUPON_returns_from_250_its_ago
R-squared: 0.0411
p-value: 0.0000

Target Symbol: ROSES
Learned Equation:
ROSES_returns_in_250_its = -0.0013 * ORCHIDS_returns_from_250_its_ago + 0.3804 * CHOCOLATE_returns_from_250_its_ago + 0.0750 * GIFT_BASKET_returns_from_250_its_ago + 0.0386 * STRAWBERRIES_returns_from_250_its_ago + -0.4939 * COCONUT_returns_from_250_its_ago + 0.0259 * COCONUT_COUPON_returns_from_250_its_ago
R-squared: 0.1564
p-value: 0.0000

Target Symbol: STRAWBERRIES
Learned Equation:
STRAWBERRIES_returns_in_250_its = -0.0164 * ORCHIDS_returns_from_250_its_ago + 0.0481 * CHOCOLATE_returns_from_250_its_ago + -0.0565 * GIFT_BASKET_returns_from_250_its_ago + 0.0285 * ROSES_returns_from_250_its_ago + 0.1836 * COCONUT_returns_from_250_its_ago + -0.0024 * COCONUT_COUPON_returns_from_250_its_ago
R-squared: 0.0726
p-value: 0.0000

Target Symbol: COCONUT
Learned Equation:
COCONUT_returns_in_250_its = -0.0135 * ORCHIDS_returns_from_250_its_ago + 0.2038 * CHOCOLATE_returns_from_250_its_ago + -0.0077 * GIFT_BASKET_returns_from_250_its_ago + 0.0981 * ROSES_returns_from_250_its_ago + -0.1571 * STRAWBERRIES_returns_from_250_its_ago
R-squared: 0.0830
p-value: 0.0000

Target Symbol: COCONUT_COUPON
Learned Equation:
COCONUT_COUPON_returns_in_250_its = -0.0320 * ORCHIDS_returns_from_250_its_ago + 1.9063 * CHOCOLATE_returns_from_250_its_ago + -1.1731 * GIFT_BASKET_returns_from_250_its_ago + 1.9883 * ROSES_returns_from_250_its_ago + -1.4833 * STRAWBERRIES_returns_from_250_its_ago + -1.4564 * COCONUT_returns_from_250_its_ago
R-squared: 0.0847
p-value: 0.0000


Timeframe: 300 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_300_its = 2.1279 * CHOCOLATE_returns_from_300_its_ago + -2.6837 * GIFT_BASKET_returns_from_300_its_ago + -1.3532 * ROSES_returns_from_300_its_ago + -0.9098 * STRAWBERRIES_returns_from_300_its_ago + -1.1874 * COCONUT_returns_from_300_its_ago + -0.0289 * COCONUT_COUPON_returns_from_300_its_ago
R-squared: 0.1864
p-value: 0.0000

Target Symbol: CHOCOLATE
Learned Equation:
CHOCOLATE_returns_in_300_its = 0.0116 * ORCHIDS_returns_from_300_its_ago + -0.0760 * GIFT_BASKET_returns_from_300_its_ago + -0.0826 * ROSES_returns_from_300_its_ago + -0.1043 * STRAWBERRIES_returns_from_300_its_ago + -0.2115 * COCONUT_returns_from_300_its_ago + 0.0210 * COCONUT_COUPON_returns_from_300_its_ago
R-squared: 0.0476
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_300_its = 0.0057 * ORCHIDS_returns_from_300_its_ago + 0.1033 * CHOCOLATE_returns_from_300_its_ago + -0.0414 * ROSES_returns_from_300_its_ago + -0.0507 * STRAWBERRIES_returns_from_300_its_ago + -0.0705 * COCONUT_returns_from_300_its_ago + 0.0145 * COCONUT_COUPON_returns_from_300_its_ago
R-squared: 0.0439
p-value: 0.0000

Target Symbol: ROSES
Learned Equation:
ROSES_returns_in_300_its = -0.0010 * ORCHIDS_returns_from_300_its_ago + 0.4599 * CHOCOLATE_returns_from_300_its_ago + -0.0444 * GIFT_BASKET_returns_from_300_its_ago + 0.0701 * STRAWBERRIES_returns_from_300_its_ago + -0.5207 * COCONUT_returns_from_300_its_ago + 0.0338 * COCONUT_COUPON_returns_from_300_its_ago
R-squared: 0.1831
p-value: 0.0000

Target Symbol: STRAWBERRIES
Learned Equation:
STRAWBERRIES_returns_in_300_its = -0.0187 * ORCHIDS_returns_from_300_its_ago + 0.0614 * CHOCOLATE_returns_from_300_its_ago + -0.0827 * GIFT_BASKET_returns_from_300_its_ago + 0.0536 * ROSES_returns_from_300_its_ago + 0.2668 * COCONUT_returns_from_300_its_ago + -0.0027 * COCONUT_COUPON_returns_from_300_its_ago
R-squared: 0.1369
p-value: 0.0000

Target Symbol: COCONUT
Learned Equation:
COCONUT_returns_in_300_its = -0.0180 * ORCHIDS_returns_from_300_its_ago + 0.2159 * CHOCOLATE_returns_from_300_its_ago + 0.0500 * GIFT_BASKET_returns_from_300_its_ago + 0.0420 * ROSES_returns_from_300_its_ago + -0.1466 * STRAWBERRIES_returns_from_300_its_ago
R-squared: 0.0820
p-value: 0.0000

Target Symbol: COCONUT_COUPON
Learned Equation:
COCONUT_COUPON_returns_in_300_its = 0.0210 * ORCHIDS_returns_from_300_its_ago + 2.2054 * CHOCOLATE_returns_from_300_its_ago + -1.6152 * GIFT_BASKET_returns_from_300_its_ago + 1.3378 * ROSES_returns_from_300_its_ago + -1.7995 * STRAWBERRIES_returns_from_300_its_ago + -1.9716 * COCONUT_returns_from_300_its_ago
R-squared: 0.0683
p-value: 0.0000


Timeframe: 350 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_350_its = 1.4628 * CHOCOLATE_returns_from_350_its_ago + -3.0256 * GIFT_BASKET_returns_from_350_its_ago + -1.5054 * ROSES_returns_from_350_its_ago + -0.9156 * STRAWBERRIES_returns_from_350_its_ago + -0.4726 * COCONUT_returns_from_350_its_ago + -0.0428 * COCONUT_COUPON_returns_from_350_its_ago
R-squared: 0.2264
p-value: 0.0000

Target Symbol: CHOCOLATE
Learned Equation:
CHOCOLATE_returns_in_350_its = 0.0151 * ORCHIDS_returns_from_350_its_ago + -0.0097 * GIFT_BASKET_returns_from_350_its_ago + -0.0838 * ROSES_returns_from_350_its_ago + -0.1489 * STRAWBERRIES_returns_from_350_its_ago + -0.2114 * COCONUT_returns_from_350_its_ago + 0.0125 * COCONUT_COUPON_returns_from_350_its_ago
R-squared: 0.0276
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_350_its = 0.0111 * ORCHIDS_returns_from_350_its_ago + 0.1222 * CHOCOLATE_returns_from_350_its_ago + -0.0534 * ROSES_returns_from_350_its_ago + -0.0504 * STRAWBERRIES_returns_from_350_its_ago + -0.0918 * COCONUT_returns_from_350_its_ago + 0.0107 * COCONUT_COUPON_returns_from_350_its_ago
R-squared: 0.0410
p-value: 0.0000

Target Symbol: ROSES
Learned Equation:
ROSES_returns_in_350_its = -0.0011 * ORCHIDS_returns_from_350_its_ago + 0.5087 * CHOCOLATE_returns_from_350_its_ago + -0.2306 * GIFT_BASKET_returns_from_350_its_ago + 0.1139 * STRAWBERRIES_returns_from_350_its_ago + -0.5749 * COCONUT_returns_from_350_its_ago + 0.0393 * COCONUT_COUPON_returns_from_350_its_ago
R-squared: 0.1902
p-value: 0.0000

Target Symbol: STRAWBERRIES
Learned Equation:
STRAWBERRIES_returns_in_350_its = -0.0179 * ORCHIDS_returns_from_350_its_ago + 0.0830 * CHOCOLATE_returns_from_350_its_ago + -0.1007 * GIFT_BASKET_returns_from_350_its_ago + 0.0855 * ROSES_returns_from_350_its_ago + 0.3001 * COCONUT_returns_from_350_its_ago + -0.0006 * COCONUT_COUPON_returns_from_350_its_ago
R-squared: 0.1894
p-value: 0.0000

Target Symbol: COCONUT
Learned Equation:
COCONUT_returns_in_350_its = -0.0231 * ORCHIDS_returns_from_350_its_ago + 0.2085 * CHOCOLATE_returns_from_350_its_ago + 0.1382 * GIFT_BASKET_returns_from_350_its_ago + -0.0306 * ROSES_returns_from_350_its_ago + -0.1462 * STRAWBERRIES_returns_from_350_its_ago
R-squared: 0.0997
p-value: 0.0000

Target Symbol: COCONUT_COUPON
Learned Equation:
COCONUT_COUPON_returns_in_350_its = -0.0050 * ORCHIDS_returns_from_350_its_ago + 1.6560 * CHOCOLATE_returns_from_350_its_ago + 0.3748 * GIFT_BASKET_returns_from_350_its_ago + 0.0220 * ROSES_returns_from_350_its_ago + -2.0382 * STRAWBERRIES_returns_from_350_its_ago + -1.8107 * COCONUT_returns_from_350_its_ago
R-squared: 0.0470
p-value: 0.0000


Timeframe: 400 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_400_its = 1.1595 * CHOCOLATE_returns_from_400_its_ago + -4.4340 * GIFT_BASKET_returns_from_400_its_ago + -1.1690 * ROSES_returns_from_400_its_ago + -0.5810 * STRAWBERRIES_returns_from_400_its_ago + 0.0907 * COCONUT_returns_from_400_its_ago + -0.0371 * COCONUT_COUPON_returns_from_400_its_ago
R-squared: 0.3018
p-value: 0.0000

Target Symbol: CHOCOLATE
Learned Equation:
CHOCOLATE_returns_in_400_its = 0.0139 * ORCHIDS_returns_from_400_its_ago + 0.1355 * GIFT_BASKET_returns_from_400_its_ago + -0.1428 * ROSES_returns_from_400_its_ago + -0.2024 * STRAWBERRIES_returns_from_400_its_ago + -0.2097 * COCONUT_returns_from_400_its_ago + 0.0042 * COCONUT_COUPON_returns_from_400_its_ago
R-squared: 0.0493
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_400_its = 0.0141 * ORCHIDS_returns_from_400_its_ago + 0.1554 * CHOCOLATE_returns_from_400_its_ago + -0.0924 * ROSES_returns_from_400_its_ago + -0.0313 * STRAWBERRIES_returns_from_400_its_ago + -0.0895 * COCONUT_returns_from_400_its_ago + 0.0067 * COCONUT_COUPON_returns_from_400_its_ago
R-squared: 0.0653
p-value: 0.0000

Target Symbol: ROSES
Learned Equation:
ROSES_returns_in_400_its = 0.0024 * ORCHIDS_returns_from_400_its_ago + 0.5291 * CHOCOLATE_returns_from_400_its_ago + -0.4027 * GIFT_BASKET_returns_from_400_its_ago + 0.1512 * STRAWBERRIES_returns_from_400_its_ago + -0.5458 * COCONUT_returns_from_400_its_ago + 0.0352 * COCONUT_COUPON_returns_from_400_its_ago
R-squared: 0.1584
p-value: 0.0000

Target Symbol: STRAWBERRIES
Learned Equation:
STRAWBERRIES_returns_in_400_its = -0.0161 * ORCHIDS_returns_from_400_its_ago + 0.1036 * CHOCOLATE_returns_from_400_its_ago + -0.0875 * GIFT_BASKET_returns_from_400_its_ago + 0.0957 * ROSES_returns_from_400_its_ago + 0.3565 * COCONUT_returns_from_400_its_ago + 0.0005 * COCONUT_COUPON_returns_from_400_its_ago
R-squared: 0.2496
p-value: 0.0000

Target Symbol: COCONUT
Learned Equation:
COCONUT_returns_in_400_its = -0.0257 * ORCHIDS_returns_from_400_its_ago + 0.1701 * CHOCOLATE_returns_from_400_its_ago + 0.2503 * GIFT_BASKET_returns_from_400_its_ago + -0.0960 * ROSES_returns_from_400_its_ago + -0.1529 * STRAWBERRIES_returns_from_400_its_ago
R-squared: 0.1049
p-value: 0.0000

Target Symbol: COCONUT_COUPON

Learned Equation:
COCONUT_COUPON_returns_in_400_its = -0.0573 * ORCHIDS_returns_from_400_its_ago + 0.3465 * CHOCOLATE_returns_from_400_its_ago + 3.1046 * GIFT_BASKET_returns_from_400_its_ago + -1.3187 * ROSES_returns_from_400_its_ago + -2.3854 * STRAWBERRIES_returns_from_400_its_ago + -0.8697 * COCONUT_returns_from_400_its_ago
R-squared: 0.0367
p-value: 0.0000


Timeframe: 500 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_500_its = 1.4783 * CHOCOLATE_returns_from_500_its_ago + -4.9401 * GIFT_BASKET_returns_from_500_its_ago + -0.8107 * ROSES_returns_from_500_its_ago + -0.3786 * STRAWBERRIES_returns_from_500_its_ago + 1.5567 * COCONUT_returns_from_500_its_ago + -0.1553 * COCONUT_COUPON_returns_from_500_its_ago
R-squared: 0.3550
p-value: 0.0000

Target Symbol: CHOCOLATE
Learned Equation:
CHOCOLATE_returns_in_500_its = 0.0048 * ORCHIDS_returns_from_500_its_ago + 0.2356 * GIFT_BASKET_returns_from_500_its_ago + -0.2152 * ROSES_returns_from_500_its_ago + -0.3096 * STRAWBERRIES_returns_from_500_its_ago + -0.1830 * COCONUT_returns_from_500_its_ago + -0.0028 * COCONUT_COUPON_returns_from_500_its_ago
R-squared: 0.0903
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_500_its = 0.0149 * ORCHIDS_returns_from_500_its_ago + 0.1939 * CHOCOLATE_returns_from_500_its_ago + -0.1710 * ROSES_returns_from_500_its_ago + -0.0163 * STRAWBERRIES_returns_from_500_its_ago + -0.0735 * COCONUT_returns_from_500_its_ago + -0.0025 * COCONUT_COUPON_returns_from_500_its_ago
R-squared: 0.1484
p-value: 0.0000

Target Symbol: ROSES
Learned Equation:
ROSES_returns_in_500_its = 0.0123 * ORCHIDS_returns_from_500_its_ago + 0.5606 * CHOCOLATE_returns_from_500_its_ago + -0.5771 * GIFT_BASKET_returns_from_500_its_ago + 0.2536 * STRAWBERRIES_returns_from_500_its_ago + -0.5094 * COCONUT_returns_from_500_its_ago + 0.0206 * COCONUT_COUPON_returns_from_500_its_ago
R-squared: 0.1434
p-value: 0.0000

Target Symbol: STRAWBERRIES
Learned Equation:
STRAWBERRIES_returns_in_500_its = -0.0110 * ORCHIDS_returns_from_500_its_ago + 0.2928 * CHOCOLATE_returns_from_500_its_ago + -0.1436 * GIFT_BASKET_returns_from_500_its_ago + 0.1207 * ROSES_returns_from_500_its_ago + 0.3851 * COCONUT_returns_from_500_its_ago + -0.0027 * COCONUT_COUPON_returns_from_500_its_ago
R-squared: 0.3326
p-value: 0.0000

Target Symbol: COCONUT
Learned Equation:
COCONUT_returns_in_500_its = -0.0329 * ORCHIDS_returns_from_500_its_ago + 0.0503 * CHOCOLATE_returns_from_500_its_ago + 0.5938 * GIFT_BASKET_returns_from_500_its_ago + -0.2460 * ROSES_returns_from_500_its_ago + -0.2100 * STRAWBERRIES_returns_from_500_its_ago
R-squared: 0.2228
p-value: 0.0000

Target Symbol: COCONUT_COUPON
Learned Equation:
COCONUT_COUPON_returns_in_500_its = -0.1102 * ORCHIDS_returns_from_500_its_ago + -1.4025 * CHOCOLATE_returns_from_500_its_ago + 7.3297 * GIFT_BASKET_returns_from_500_its_ago + -3.7087 * ROSES_returns_from_500_its_ago + -1.1005 * STRAWBERRIES_returns_from_500_its_ago + -0.6877 * COCONUT_returns_from_500_its_ago
R-squared: 0.1392
p-value: 0.0000

In [75]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import scipy.stats as stats

timeframes = [1, 2, 3, 5, 7, 10, 15, 25, 50, 75, 100, 150, 200, 250, 300, 350, 400, 500]
symbols = ['ORCHIDS','GIFT_BASKET']

df_copy = df.copy()

for timeframe in timeframes:
    print(f"Timeframe: {timeframe} iterations")
    
    # Add lagged and future returns columns for each symbol
    for symbol in symbols:
        df_copy = get_prev_returns(df_copy, symbol, timeframe)
        df_copy = get_future_returns(df_copy, symbol, timeframe)
    
    for target_symbol in symbols:
        print(f"Target Symbol: {target_symbol}")
        
        # Get the feature columns (lagged returns from other symbols)
        feature_cols = [col for col in df_copy.columns if col.endswith(f"_returns_from_{timeframe}_its_ago") and not col.startswith(target_symbol)]
        
        # Get the target column (future returns for the target symbol)
        target_col = f"{target_symbol}_returns_in_{timeframe}_its"
        
        # Drop rows with missing values
        df_train = df_copy[feature_cols + [target_col]].dropna()
        
        # Split the data into features (X) and target (y)
        X = df_train[feature_cols]
        y = df_train[target_col]
        
        # Create and fit the linear regression model (without y-intercept)
        model = LinearRegression(fit_intercept=False)
        model.fit(X, y)
        
        # Print the learned equation
        equation = f"{target_col} = " + " + ".join([f"{coef:.4f} * {feat}" for feat, coef in zip(feature_cols, model.coef_)])
        print("Learned Equation:")
        print(equation)
        
        # Make predictions on the training data
        y_pred = model.predict(X)
        
        # Calculate and print the R-squared and p-value
        r2 = r2_score(y, y_pred)
        print(f"R-squared: {r2:.4f}")
        
        _, p_value = stats.pearsonr(y, y_pred)
        print(f"p-value: {p_value:.4f}")
        
        print()
    
    df_copy = df_copy[['timestamp'] + symbols]
    
    print()

Timeframe: 1 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_1_its = 0.2311 * GIFT_BASKET_returns_from_1_its_ago
R-squared: 0.0006
p-value: 0.0118

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_1_its = -0.0013 * ORCHIDS_returns_from_1_its_ago
R-squared: 0.0001
p-value: 0.2233


Timeframe: 2 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_2_its = 0.0349 * GIFT_BASKET_returns_from_2_its_ago
R-squared: -0.0000
p-value: 0.7134

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_2_its = -0.0004 * ORCHIDS_returns_from_2_its_ago
R-squared: -0.0001
p-value: 0.6933


Timeframe: 3 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_3_its = -0.0303 * GIFT_BASKET_returns_from_3_its_ago
R-squared: -0.0001
p-value: 0.7389

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_3_its = -0.0014 * ORCHIDS_returns_from_3_its_ago
R-squared: 0.0000
p-value: 0.1950


Timeframe: 5 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_5_its = -0.0073 * GIFT_BASKET_returns_from_5_its_ago
R-squared: -0.0001
p-value: 0.9250

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_5_its = -0.0030 * ORCHIDS_returns_from_5_its_ago
R-squared: 0.0005
p-value: 0.0049


Timeframe: 7 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_7_its = -0.2459 * GIFT_BASKET_returns_from_7_its_ago
R-squared: 0.0005
p-value: 0.0084

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_7_its = -0.0006 * ORCHIDS_returns_from_7_its_ago
R-squared: -0.0003
p-value: 0.5711


Timeframe: 10 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_10_its = -0.3832 * GIFT_BASKET_returns_from_10_its_ago
R-squared: 0.0014
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_10_its = -0.0002 * ORCHIDS_returns_from_10_its_ago
R-squared: -0.0005
p-value: 0.8177


Timeframe: 15 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_15_its = -0.2697 * GIFT_BASKET_returns_from_15_its_ago
R-squared: 0.0005
p-value: 0.0038

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_15_its = -0.0014 * ORCHIDS_returns_from_15_its_ago
R-squared: -0.0006
p-value: 0.1907


Timeframe: 25 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_25_its = 0.2889 * GIFT_BASKET_returns_from_25_its_ago
R-squared: 0.0004
p-value: 0.0035

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_25_its = -0.0022 * ORCHIDS_returns_from_25_its_ago
R-squared: -0.0009
p-value: 0.0297


Timeframe: 50 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_50_its = -0.1879 * GIFT_BASKET_returns_from_50_its_ago
R-squared: -0.0003
p-value: 0.0411

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_50_its = -0.0009 * ORCHIDS_returns_from_50_its_ago
R-squared: -0.0021
p-value: 0.3123


Timeframe: 75 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_75_its = -0.5661 * GIFT_BASKET_returns_from_75_its_ago
R-squared: 0.0026
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_75_its = 0.0032 * ORCHIDS_returns_from_75_its_ago
R-squared: -0.0017
p-value: 0.0024


Timeframe: 100 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_100_its = -0.5403 * GIFT_BASKET_returns_from_100_its_ago
R-squared: 0.0022
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_100_its = 0.0082 * ORCHIDS_returns_from_100_its_ago
R-squared: 0.0030
p-value: 0.0000


Timeframe: 150 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_150_its = -0.7249 * GIFT_BASKET_returns_from_150_its_ago
R-squared: 0.0044
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_150_its = 0.0033 * ORCHIDS_returns_from_150_its_ago
R-squared: -0.0061
p-value: 0.0025


Timeframe: 200 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_200_its = -0.9039 * GIFT_BASKET_returns_from_200_its_ago
R-squared: 0.0064
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_200_its = -0.0049 * ORCHIDS_returns_from_200_its_ago
R-squared: -0.0078
p-value: 0.0000


Timeframe: 250 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_250_its = -1.2213 * GIFT_BASKET_returns_from_250_its_ago
R-squared: 0.0118
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_250_its = -0.0039 * ORCHIDS_returns_from_250_its_ago
R-squared: -0.0111
p-value: 0.0001


Timeframe: 300 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_300_its = -2.3526 * GIFT_BASKET_returns_from_300_its_ago
R-squared: 0.0487
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_300_its = 0.0014 * ORCHIDS_returns_from_300_its_ago
R-squared: -0.0150
p-value: 0.2538


Timeframe: 350 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_350_its = -3.5481 * GIFT_BASKET_returns_from_350_its_ago
R-squared: 0.1197
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_350_its = 0.0072 * ORCHIDS_returns_from_350_its_ago
R-squared: -0.0141
p-value: 0.0000


Timeframe: 400 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_400_its = -4.9311 * GIFT_BASKET_returns_from_400_its_ago
R-squared: 0.2448
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_400_its = 0.0120 * ORCHIDS_returns_from_400_its_ago
R-squared: -0.0092
p-value: 0.0000


Timeframe: 500 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_500_its = -5.2917 * GIFT_BASKET_returns_from_500_its_ago
R-squared: 0.2920
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_in_500_its = 0.0187 * ORCHIDS_returns_from_500_its_ago
R-squared: 0.0081
p-value: 0.0000

In [76]:
df

,timestamp,ORCHIDS,TRANSPORT_FEES,EXPORT_TARIFF,IMPORT_TARIFF,SUNLIGHT,HUMIDITY,DAY,CHOCOLATE,GIFT_BASKET,ROSES,STRAWBERRIES,COCONUT,COCONUT_COUPON
0,0,1098.25,0.9,10.5,-5.0,2100.0000,70.000000,1,7988.0,71114.5,14545.5,4030.5,10000.0,637.5
1,100,1098.25,0.9,9.5,-5.0,2099.7570,70.022710,1,7988.0,71114.0,14543.5,4030.5,9999.5,637.5
2,200,1096.75,0.9,9.5,-5.0,2099.5132,70.045395,1,7987.5,71115.5,14543.5,4030.0,9998.5,637.5
3,300,1097.00,0.9,9.5,-5.0,2099.2683,70.068030,1,7988.5,71123.5,14541.5,4030.0,9999.5,638.5
4,400,1097.25,0.9,9.5,-5.0,2099.0225,70.090640,1,7989.5,71132.5,14547.5,4030.0,9998.5,637.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,999600,1036.25,0.9,9.5,-5.0,2299.9436,69.935490,1,7885.5,70599.5,14418.0,4036.5,10136.5,682.5
9997,999700,1036.25,0.9,9.5,-5.0,2299.9556,69.951530,1,7885.5,70585.5,14421.5,4035.5,10134.5,681.5
9998,999800,1036.25,0.9,9.5,-5.0,2299.9690,69.967620,1,7887.5,70584.5,14419.0,4035.5,10135.0,681.5
9999,999900,1034.25,0.9,9.5,-5.0,2299.9840,69.983780,1,7887.5,70586.5,14422.5,4036.0,10135.0,682.5
10000,1000000,1035.25,0.9,9.5,-5.0,2300.0000,70.000000,1,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
import plotly.graph_objects as go

# Create traces for ORCHIDS and GIFT_BASKET prices
trace_orchids = go.Scatter(
    x=df['timestamp'],
    y=df['ORCHIDS'],
    mode='lines',
    name='ORCHIDS',
    yaxis='y1'  # Assign the trace to the first y-axis
)

trace_gift_basket = go.Scatter(
    x=df['timestamp'],
    y=df['GIFT_BASKET'],
    mode='lines',
    name='GIFT_BASKET',
    yaxis='y2'  # Assign the trace to the second y-axis
)

# Create the layout for the plot
layout = go.Layout(
    title='ORCHIDS and GIFT_BASKET Prices Over Time',
    xaxis=dict(title='Timestamp'),
    yaxis=dict(
        title='ORCHIDS Price',
        titlefont=dict(color='blue'),
        tickfont=dict(color='blue')
    ),
    yaxis2=dict(
        title='GIFT_BASKET Price',
        titlefont=dict(color='green'),
        tickfont=dict(color='green'),
        overlaying='y',
        side='right'
    )
)

# Create the figure and add the traces and layout
fig = go.Figure(data=[trace_orchids, trace_gift_basket], layout=layout)

# Display the plot
fig.show()

In [78]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import scipy.stats as stats

timeframes = [1, 2, 3, 5, 7, 10, 15, 25, 50, 75, 100, 150, 200, 250, 300, 350, 400, 500]
symbols = ['ORCHIDS','GIFT_BASKET']

df_copy = df.copy()

for timeframe in timeframes:
    print(f"Timeframe: {timeframe} iterations")
    
    # Add lagged and future returns columns for each symbol
    for symbol in symbols:
        df_copy = get_prev_returns(df_copy, symbol, timeframe)
        df_copy = get_future_returns(df_copy, symbol, timeframe)
    
    for target_symbol in symbols:
        print(f"Target Symbol: {target_symbol}")
        
        # Get the feature columns (lagged returns from other symbols)
        feature_cols = [col for col in df_copy.columns if col.endswith(f"_returns_from_{timeframe}_its_ago") and not col.startswith(target_symbol)]
        
        # Get the target column (future returns for the target symbol)
        target_col = f"{target_symbol}_returns_from_{timeframe}_its_ago"
        
        # Drop rows with missing values
        df_train = df_copy[feature_cols + [target_col]].dropna()
        
        # Split the data into features (X) and target (y)
        X = df_train[feature_cols]
        y = df_train[target_col]
        
        # Create and fit the linear regression model (without y-intercept)
        model = LinearRegression(fit_intercept=False)
        model.fit(X, y)
        
        # Print the learned equation
        equation = f"{target_col} = " + " + ".join([f"{coef:.4f} * {feat}" for feat, coef in zip(feature_cols, model.coef_)])
        print("Learned Equation:")
        print(equation)
        
        # Make predictions on the training data
        y_pred = model.predict(X)
        
        # Calculate and print the R-squared and p-value
        r2 = r2_score(y, y_pred)
        print(f"R-squared: {r2:.4f}")
        
        _, p_value = stats.pearsonr(y, y_pred)
        print(f"p-value: {p_value:.4f}")
        
        print()
    
    df_copy = df_copy[['timestamp'] + symbols]
    
    print()

Timeframe: 1 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_from_1_its_ago = 0.0589 * GIFT_BASKET_returns_from_1_its_ago
R-squared: 0.0000
p-value: 0.5226

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_from_1_its_ago = 0.0007 * ORCHIDS_returns_from_1_its_ago
R-squared: -0.0000
p-value: 0.5226


Timeframe: 2 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_from_2_its_ago = 0.1216 * GIFT_BASKET_returns_from_2_its_ago
R-squared: 0.0001
p-value: 0.1941

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_from_2_its_ago = 0.0014 * ORCHIDS_returns_from_2_its_ago
R-squared: 0.0001
p-value: 0.1941


Timeframe: 3 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_from_3_its_ago = 0.0979 * GIFT_BASKET_returns_from_3_its_ago
R-squared: 0.0000
p-value: 0.3009

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_from_3_its_ago = 0.0011 * ORCHIDS_returns_from_3_its_ago
R-squared: -0.0000
p-value: 0.3009


Timeframe: 5 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_from_5_its_ago = 0.0581 * GIFT_BASKET_returns_from_5_its_ago
R-squared: -0.0001
p-value: 0.5490

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_from_5_its_ago = 0.0007 * ORCHIDS_returns_from_5_its_ago
R-squared: -0.0002
p-value: 0.5490


Timeframe: 7 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_from_7_its_ago = -0.0119 * GIFT_BASKET_returns_from_7_its_ago
R-squared: -0.0002
p-value: 0.8817

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_from_7_its_ago = -0.0001 * ORCHIDS_returns_from_7_its_ago
R-squared: -0.0003
p-value: 0.8817


Timeframe: 10 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_from_10_its_ago = -0.0721 * GIFT_BASKET_returns_from_10_its_ago
R-squared: -0.0002
p-value: 0.4254

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_from_10_its_ago = -0.0008 * ORCHIDS_returns_from_10_its_ago
R-squared: -0.0004
p-value: 0.4254


Timeframe: 15 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_from_15_its_ago = -0.1836 * GIFT_BASKET_returns_from_15_its_ago
R-squared: 0.0001
p-value: 0.0470

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_from_15_its_ago = -0.0021 * ORCHIDS_returns_from_15_its_ago
R-squared: -0.0003
p-value: 0.0470


Timeframe: 25 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_from_25_its_ago = -0.3258 * GIFT_BASKET_returns_from_25_its_ago
R-squared: 0.0007
p-value: 0.0005

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_from_25_its_ago = -0.0035 * ORCHIDS_returns_from_25_its_ago
R-squared: -0.0001
p-value: 0.0005


Timeframe: 50 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_from_50_its_ago = -0.2885 * GIFT_BASKET_returns_from_50_its_ago
R-squared: 0.0001
p-value: 0.0020

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_from_50_its_ago = -0.0030 * ORCHIDS_returns_from_50_its_ago
R-squared: -0.0017
p-value: 0.0020


Timeframe: 75 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_from_75_its_ago = -0.3304 * GIFT_BASKET_returns_from_75_its_ago
R-squared: 0.0000
p-value: 0.0004

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_from_75_its_ago = -0.0033 * ORCHIDS_returns_from_75_its_ago
R-squared: -0.0026
p-value: 0.0004


Timeframe: 100 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_from_100_its_ago = -0.4662 * GIFT_BASKET_returns_from_100_its_ago
R-squared: 0.0009
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_from_100_its_ago = -0.0047 * ORCHIDS_returns_from_100_its_ago
R-squared: -0.0024
p-value: 0.0000


Timeframe: 150 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_from_150_its_ago = -0.5277 * GIFT_BASKET_returns_from_150_its_ago
R-squared: 0.0015
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_from_150_its_ago = -0.0052 * ORCHIDS_returns_from_150_its_ago
R-squared: -0.0039
p-value: 0.0000


Timeframe: 200 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_from_200_its_ago = -0.4001 * GIFT_BASKET_returns_from_200_its_ago
R-squared: -0.0001
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_from_200_its_ago = -0.0038 * ORCHIDS_returns_from_200_its_ago
R-squared: -0.0073
p-value: 0.0000


Timeframe: 250 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_from_250_its_ago = -0.5691 * GIFT_BASKET_returns_from_250_its_ago
R-squared: 0.0011
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_from_250_its_ago = -0.0053 * ORCHIDS_returns_from_250_its_ago
R-squared: -0.0083
p-value: 0.0000


Timeframe: 300 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_from_300_its_ago = -0.8517 * GIFT_BASKET_returns_from_300_its_ago
R-squared: 0.0048
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_from_300_its_ago = -0.0081 * ORCHIDS_returns_from_300_its_ago
R-squared: -0.0068
p-value: 0.0000


Timeframe: 350 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_from_350_its_ago = -1.2172 * GIFT_BASKET_returns_from_350_its_ago
R-squared: 0.0125
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_from_350_its_ago = -0.0121 * ORCHIDS_returns_from_350_its_ago
R-squared: -0.0002
p-value: 0.0000


Timeframe: 400 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_from_400_its_ago = -1.3824 * GIFT_BASKET_returns_from_400_its_ago
R-squared: 0.0175
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_from_400_its_ago = -0.0143 * ORCHIDS_returns_from_400_its_ago
R-squared: 0.0031
p-value: 0.0000


Timeframe: 500 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_from_500_its_ago = -1.7176 * GIFT_BASKET_returns_from_500_its_ago
R-squared: 0.0296
p-value: 0.0000

Target Symbol: GIFT_BASKET
Learned Equation:
GIFT_BASKET_returns_from_500_its_ago = -0.0182 * ORCHIDS_returns_from_500_its_ago
R-squared: 0.0116
p-value: 0.0000

In [79]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import scipy.stats as stats

timeframes = [1, 2, 3, 5, 7, 10, 15, 25, 50, 75, 100, 150, 200, 250, 300, 350, 400, 500, 600, 700, 800, 900, 1000]
predictor_symbols = ['GIFT_BASKET']
responder_symbols = ['ORCHIDS']

df_copy = df.copy()

for timeframe in timeframes:
    print(f"Timeframe: {timeframe} iterations")
    
    # Add lagged and future returns columns for each symbol
    for symbol in predictor_symbols + responder_symbols:
        df_copy = get_prev_returns(df_copy, symbol, timeframe)
        df_copy = get_future_returns(df_copy, symbol, timeframe)
    
    for target_symbol in responder_symbols:
        print(f"Target Symbol: {target_symbol}")
        
        # Get the feature columns (lagged returns from predictor symbols)
        feature_cols = [col for col in df_copy.columns if col.endswith(f"_returns_from_{timeframe}_its_ago") and any(col.startswith(symbol) for symbol in predictor_symbols)]
        
        # Get the target column (future returns for the target symbol)
        target_col = f"{target_symbol}_returns_in_{timeframe}_its"
        
        # Drop rows with missing values
        df_train = df_copy[feature_cols + [target_col]].dropna()
        
        # Split the data into features (X) and target (y)
        X = df_train[feature_cols]
        y = df_train[target_col]
        
        # Create and fit the linear regression model (without y-intercept)
        model = LinearRegression(fit_intercept=False)
        model.fit(X, y)
        
        # Print the learned equation
        equation = f"{target_col} = " + " + ".join([f"{coef:.4f} * {feat}" for feat, coef in zip(feature_cols, model.coef_)])
        print("Learned Equation:")
        print(equation)
        
        # Make predictions on the training data
        y_pred = model.predict(X)
        
        # Calculate and print the R-squared and p-value
        r2 = r2_score(y, y_pred)
        print(f"R-squared: {r2:.4f}")
        
        _, p_value = stats.pearsonr(y, y_pred)
        print(f"p-value: {p_value:.4f}")
        
        print()
    
    df_copy = df_copy[['timestamp'] + predictor_symbols + responder_symbols]
    print()

Timeframe: 1 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_1_its = 0.2311 * GIFT_BASKET_returns_from_1_its_ago
R-squared: 0.0006
p-value: 0.0118


Timeframe: 2 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_2_its = 0.0349 * GIFT_BASKET_returns_from_2_its_ago
R-squared: -0.0000
p-value: 0.7134


Timeframe: 3 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_3_its = -0.0303 * GIFT_BASKET_returns_from_3_its_ago
R-squared: -0.0001
p-value: 0.7389


Timeframe: 5 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_5_its = -0.0073 * GIFT_BASKET_returns_from_5_its_ago
R-squared: -0.0001
p-value: 0.9250


Timeframe: 7 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_7_its = -0.2459 * GIFT_BASKET_returns_from_7_its_ago
R-squared: 0.0005
p-value: 0.0084


Timeframe: 10 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_10_its = -0.3832 * GIFT_BASKET_returns_from_10_its_ago
R-squared: 0.0014
p-value: 0.0000


Timeframe: 15 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_15_its = -0.2697 * GIFT_BASKET_returns_from_15_its_ago
R-squared: 0.0005
p-value: 0.0038


Timeframe: 25 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_25_its = 0.2889 * GIFT_BASKET_returns_from_25_its_ago
R-squared: 0.0004
p-value: 0.0035


Timeframe: 50 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_50_its = -0.1879 * GIFT_BASKET_returns_from_50_its_ago
R-squared: -0.0003
p-value: 0.0411


Timeframe: 75 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_75_its = -0.5661 * GIFT_BASKET_returns_from_75_its_ago
R-squared: 0.0026
p-value: 0.0000


Timeframe: 100 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_100_its = -0.5403 * GIFT_BASKET_returns_from_100_its_ago
R-squared: 0.0022
p-value: 0.0000


Timeframe: 150 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_150_its = -0.7249 * GIFT_BASKET_returns_from_150_its_ago
R-squared: 0.0044
p-value: 0.0000


Timeframe: 200 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_200_its = -0.9039 * GIFT_BASKET_returns_from_200_its_ago
R-squared: 0.0064
p-value: 0.0000


Timeframe: 250 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_250_its = -1.2213 * GIFT_BASKET_returns_from_250_its_ago
R-squared: 0.0118
p-value: 0.0000


Timeframe: 300 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_300_its = -2.3526 * GIFT_BASKET_returns_from_300_its_ago
R-squared: 0.0487
p-value: 0.0000


Timeframe: 350 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_350_its = -3.5481 * GIFT_BASKET_returns_from_350_its_ago
R-squared: 0.1197
p-value: 0.0000


Timeframe: 400 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_400_its = -4.9311 * GIFT_BASKET_returns_from_400_its_ago
R-squared: 0.2448
p-value: 0.0000


Timeframe: 500 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_500_its = -5.2917 * GIFT_BASKET_returns_from_500_its_ago
R-squared: 0.2920
p-value: 0.0000


Timeframe: 600 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_600_its = -4.7761 * GIFT_BASKET_returns_from_600_its_ago
R-squared: 0.2242
p-value: 0.0000


Timeframe: 700 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_700_its = -3.3190 * GIFT_BASKET_returns_from_700_its_ago
R-squared: 0.1044
p-value: 0.0000


Timeframe: 800 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_800_its = -1.0603 * GIFT_BASKET_returns_from_800_its_ago
R-squared: 0.0096
p-value: 0.0000


Timeframe: 900 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_900_its = 0.2384 * GIFT_BASKET_returns_from_900_its_ago
R-squared: -0.0030
p-value: 0.2403


Timeframe: 1000 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_1000_its = 1.3802 * GIFT_BASKET_returns_from_1000_its_ago
R-squared: 0.0083
p-value: 0.0000

In [83]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import scipy.stats as stats

predictor_timeframes = [50, 75, 100, 150, 200, 250, 300, 350, 400, 500]
responder_timeframes = [50, 75, 100, 150, 200, 250, 300, 350, 400, 500]
predictor_symbols = ['GIFT_BASKET']
responder_symbols = ['ORCHIDS']

df_copy = df.copy()

for responder_timeframe in responder_timeframes:
    print(f"Responder Timeframe: {responder_timeframe} iterations")
    
    # Add future returns columns for responder symbols
    for symbol in responder_symbols:
        df_copy = get_future_returns(df_copy, symbol, responder_timeframe)
    
    for predictor_timeframe in predictor_timeframes:
        print(f"Predictor Timeframe: {predictor_timeframe} iterations")
        
        # Add lagged returns columns for predictor symbols
        for symbol in predictor_symbols:
            df_copy = get_prev_returns(df_copy, symbol, predictor_timeframe)
        
        for target_symbol in responder_symbols:
            print(f"Target Symbol: {target_symbol}")
            
            # Get the feature columns (lagged returns from predictor symbols)
            feature_cols = [col for col in df_copy.columns if col.endswith(f"_returns_from_{predictor_timeframe}_its_ago") and any(col.startswith(symbol) for symbol in predictor_symbols)]
            
            # Get the target column (future returns for the target symbol)
            target_col = f"{target_symbol}_returns_in_{responder_timeframe}_its"
            
            # Drop rows with missing values
            df_train = df_copy[feature_cols + [target_col]].dropna()
            
            # Split the data into features (X) and target (y)
            X = df_train[feature_cols]
            y = df_train[target_col]
            
            # Create and fit the linear regression model (without y-intercept)
            model = LinearRegression(fit_intercept=False)
            model.fit(X, y)
            
            # Print the learned equation
            equation = f"{target_col} = " + " + ".join([f"{coef:.4f} * {feat}" for feat, coef in zip(feature_cols, model.coef_)])
            print("Learned Equation:")
            print(equation)
            
            # Make predictions on the training data
            y_pred = model.predict(X)
            
            # Calculate and print the R-squared and p-value
            r2 = r2_score(y, y_pred)
            print(f"R-squared: {r2:.4f}")
            
            _, p_value = stats.pearsonr(y, y_pred)
            print(f"p-value: {p_value:.4f}")
            
            print()
        
        # Remove lagged returns columns for predictor symbols
        lagged_cols = [col for col in df_copy.columns if col.endswith(f"_returns_from_{predictor_timeframe}_its_ago")]
        df_copy.drop(columns=lagged_cols, inplace=True)
    
    # Remove future returns columns for responder symbols
    future_cols = [col for col in df_copy.columns if col.endswith(f"_returns_in_{responder_timeframe}_its")]
    df_copy.drop(columns=future_cols, inplace=True)
    
    print()

Responder Timeframe: 50 iterations
Predictor Timeframe: 50 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_50_its = -0.1879 * GIFT_BASKET_returns_from_50_its_ago
R-squared: -0.0003
p-value: 0.0411

Predictor Timeframe: 75 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_50_its = -0.3882 * GIFT_BASKET_returns_from_75_its_ago
R-squared: 0.0018
p-value: 0.0000

Predictor Timeframe: 100 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_50_its = -0.3698 * GIFT_BASKET_returns_from_100_its_ago
R-squared: 0.0024
p-value: 0.0000

Predictor Timeframe: 150 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_50_its = -0.1892 * GIFT_BASKET_returns_from_150_its_ago
R-squared: 0.0006
p-value: 0.0006

Predictor Timeframe: 200 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_50_its = -0.2760 * GIFT_BASKET_returns_from_200_its_ago
R-squared: 0.0024
p-value: 0.0000

Predictor Timeframe: 250 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_50_its = -0.2709 * GIFT_BASKET_returns_from_250_its_ago
R-squared: 0.0029
p-value: 0.0000

Predictor Timeframe: 300 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_50_its = -0.2471 * GIFT_BASKET_returns_from_300_its_ago
R-squared: 0.0026
p-value: 0.0000

Predictor Timeframe: 350 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_50_its = -0.1640 * GIFT_BASKET_returns_from_350_its_ago
R-squared: 0.0010
p-value: 0.0000

Predictor Timeframe: 400 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_50_its = -0.2598 * GIFT_BASKET_returns_from_400_its_ago
R-squared: 0.0039
p-value: 0.0000

Predictor Timeframe: 500 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_50_its = -0.4539 * GIFT_BASKET_returns_from_500_its_ago
R-squared: 0.0161
p-value: 0.0000


Responder Timeframe: 75 iterations
Predictor Timeframe: 50 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_75_its = -0.5532 * GIFT_BASKET_returns_from_50_its_ago
R-squared: 0.0013
p-value: 0.0000

Predictor Timeframe: 75 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_75_its = -0.5661 * GIFT_BASKET_returns_from_75_its_ago
R-squared: 0.0026
p-value: 0.0000

Predictor Timeframe: 100 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_75_its = -0.4513 * GIFT_BASKET_returns_from_100_its_ago
R-squared: 0.0021
p-value: 0.0000

Predictor Timeframe: 150 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_75_its = -0.3158 * GIFT_BASKET_returns_from_150_its_ago
R-squared: 0.0013
p-value: 0.0000

Predictor Timeframe: 200 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_75_its = -0.4510 * GIFT_BASKET_returns_from_200_its_ago
R-squared: 0.0045
p-value: 0.0000

Predictor Timeframe: 250 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_75_its = -0.4112 * GIFT_BASKET_returns_from_250_its_ago
R-squared: 0.0043
p-value: 0.0000

Predictor Timeframe: 300 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_75_its = -0.3468 * GIFT_BASKET_returns_from_300_its_ago
R-squared: 0.0033
p-value: 0.0000

Predictor Timeframe: 350 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_75_its = -0.2954 * GIFT_BASKET_returns_from_350_its_ago
R-squared: 0.0026
p-value: 0.0000

Predictor Timeframe: 400 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_75_its = -0.4263 * GIFT_BASKET_returns_from_400_its_ago
R-squared: 0.0072
p-value: 0.0000

Predictor Timeframe: 500 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_75_its = -0.7757 * GIFT_BASKET_returns_from_500_its_ago
R-squared: 0.0310
p-value: 0.0000


Responder Timeframe: 100 iterations
Predictor Timeframe: 50 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_100_its = -0.6637 * GIFT_BASKET_returns_from_50_its_ago
R-squared: 0.0014
p-value: 0.0000

Predictor Timeframe: 75 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_100_its = -0.5803 * GIFT_BASKET_returns_from_75_its_ago
R-squared: 0.0018
p-value: 0.0000

Predictor Timeframe: 100 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_100_its = -0.5403 * GIFT_BASKET_returns_from_100_its_ago
R-squared: 0.0022
p-value: 0.0000

Predictor Timeframe: 150 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_100_its = -0.4836 * GIFT_BASKET_returns_from_150_its_ago
R-squared: 0.0027
p-value: 0.0000

Predictor Timeframe: 200 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_100_its = -0.5595 * GIFT_BASKET_returns_from_200_its_ago
R-squared: 0.0051
p-value: 0.0000

Predictor Timeframe: 250 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_100_its = -0.5393 * GIFT_BASKET_returns_from_250_its_ago
R-squared: 0.0056
p-value: 0.0000

Predictor Timeframe: 300 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_100_its = -0.4228 * GIFT_BASKET_returns_from_300_its_ago
R-squared: 0.0036
p-value: 0.0000

Predictor Timeframe: 350 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_100_its = -0.4435 * GIFT_BASKET_returns_from_350_its_ago
R-squared: 0.0048
p-value: 0.0000

Predictor Timeframe: 400 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_100_its = -0.5827 * GIFT_BASKET_returns_from_400_its_ago
R-squared: 0.0102
p-value: 0.0000

Predictor Timeframe: 500 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_100_its = -1.0844 * GIFT_BASKET_returns_from_500_its_ago
R-squared: 0.0453
p-value: 0.0000


Responder Timeframe: 150 iterations
Predictor Timeframe: 50 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_150_its = -0.5507 * GIFT_BASKET_returns_from_50_its_ago
R-squared: 0.0001
p-value: 0.0008

Predictor Timeframe: 75 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_150_its = -0.6812 * GIFT_BASKET_returns_from_75_its_ago
R-squared: 0.0015
p-value: 0.0000

Predictor Timeframe: 100 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_150_its = -0.7778 * GIFT_BASKET_returns_from_100_its_ago
R-squared: 0.0033
p-value: 0.0000

Predictor Timeframe: 150 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_150_its = -0.7249 * GIFT_BASKET_returns_from_150_its_ago
R-squared: 0.0044
p-value: 0.0000

Predictor Timeframe: 200 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_150_its = -0.7866 * GIFT_BASKET_returns_from_200_its_ago
R-squared: 0.0068
p-value: 0.0000

Predictor Timeframe: 250 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_150_its = -0.6716 * GIFT_BASKET_returns_from_250_its_ago
R-squared: 0.0056
p-value: 0.0000

Predictor Timeframe: 300 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_150_its = -0.6857 * GIFT_BASKET_returns_from_300_its_ago
R-squared: 0.0068
p-value: 0.0000

Predictor Timeframe: 350 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_150_its = -0.7611 * GIFT_BASKET_returns_from_350_its_ago
R-squared: 0.0102
p-value: 0.0000

Predictor Timeframe: 400 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_150_its = -1.0798 * GIFT_BASKET_returns_from_400_its_ago
R-squared: 0.0244
p-value: 0.0000

Predictor Timeframe: 500 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_150_its = -1.6823 * GIFT_BASKET_returns_from_500_its_ago
R-squared: 0.0739
p-value: 0.0000


Responder Timeframe: 200 iterations
Predictor Timeframe: 50 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_200_its = -1.0429 * GIFT_BASKET_returns_from_50_its_ago
R-squared: 0.0015
p-value: 0.0000

Predictor Timeframe: 75 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_200_its = -1.1934 * GIFT_BASKET_returns_from_75_its_ago
R-squared: 0.0043
p-value: 0.0000

Predictor Timeframe: 100 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_200_its = -1.1213 * GIFT_BASKET_returns_from_100_its_ago
R-squared: 0.0053
p-value: 0.0000

Predictor Timeframe: 150 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_200_its = -0.9694 * GIFT_BASKET_returns_from_150_its_ago
R-squared: 0.0058
p-value: 0.0000

Predictor Timeframe: 200 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_200_its = -0.9039 * GIFT_BASKET_returns_from_200_its_ago
R-squared: 0.0064
p-value: 0.0000

Predictor Timeframe: 250 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_200_its = -0.9454 * GIFT_BASKET_returns_from_250_its_ago
R-squared: 0.0084
p-value: 0.0000

Predictor Timeframe: 300 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_200_its = -1.0152 * GIFT_BASKET_returns_from_300_its_ago
R-squared: 0.0116
p-value: 0.0000

Predictor Timeframe: 350 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_200_its = -1.2995 * GIFT_BASKET_returns_from_350_its_ago
R-squared: 0.0232
p-value: 0.0000

Predictor Timeframe: 400 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_200_its = -1.7833 * GIFT_BASKET_returns_from_400_its_ago
R-squared: 0.0508
p-value: 0.0000

Predictor Timeframe: 500 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_200_its = -2.3801 * GIFT_BASKET_returns_from_500_its_ago
R-squared: 0.1124
p-value: 0.0000


Responder Timeframe: 250 iterations
Predictor Timeframe: 50 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_250_its = -1.2132 * GIFT_BASKET_returns_from_50_its_ago
R-squared: 0.0016
p-value: 0.0000

Predictor Timeframe: 75 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_250_its = -1.2794 * GIFT_BASKET_returns_from_75_its_ago
R-squared: 0.0037
p-value: 0.0000

Predictor Timeframe: 100 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_250_its = -1.2558 * GIFT_BASKET_returns_from_100_its_ago
R-squared: 0.0052
p-value: 0.0000

Predictor Timeframe: 150 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_250_its = -0.9637 * GIFT_BASKET_returns_from_150_its_ago
R-squared: 0.0041
p-value: 0.0000

Predictor Timeframe: 200 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_250_its = -1.0989 * GIFT_BASKET_returns_from_200_its_ago
R-squared: 0.0076
p-value: 0.0000

Predictor Timeframe: 250 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_250_its = -1.2213 * GIFT_BASKET_returns_from_250_its_ago
R-squared: 0.0118
p-value: 0.0000

Predictor Timeframe: 300 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_250_its = -1.5419 * GIFT_BASKET_returns_from_300_its_ago
R-squared: 0.0229
p-value: 0.0000

Predictor Timeframe: 350 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_250_its = -2.0138 * GIFT_BASKET_returns_from_350_its_ago
R-squared: 0.0467
p-value: 0.0000

Predictor Timeframe: 400 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_250_its = -2.4157 * GIFT_BASKET_returns_from_400_its_ago
R-squared: 0.0771
p-value: 0.0000

Predictor Timeframe: 500 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_250_its = -3.1419 * GIFT_BASKET_returns_from_500_its_ago
R-squared: 0.1616
p-value: 0.0000


Responder Timeframe: 300 iterations
Predictor Timeframe: 50 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_300_its = -1.3988 * GIFT_BASKET_returns_from_50_its_ago
R-squared: 0.0018
p-value: 0.0000

Predictor Timeframe: 75 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_300_its = -1.3349 * GIFT_BASKET_returns_from_75_its_ago
R-squared: 0.0032
p-value: 0.0000

Predictor Timeframe: 100 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_300_its = -1.2138 * GIFT_BASKET_returns_from_100_its_ago

R-squared: 0.0037
p-value: 0.0000

Predictor Timeframe: 150 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_300_its = -1.1743 * GIFT_BASKET_returns_from_150_its_ago
R-squared: 0.0056
p-value: 0.0000

Predictor Timeframe: 200 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_300_its = -1.4172 * GIFT_BASKET_returns_from_200_its_ago
R-squared: 0.0118
p-value: 0.0000

Predictor Timeframe: 250 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_300_its = -1.8118 * GIFT_BASKET_returns_from_250_its_ago
R-squared: 0.0242
p-value: 0.0000

Predictor Timeframe: 300 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_300_its = -2.3526 * GIFT_BASKET_returns_from_300_its_ago
R-squared: 0.0487
p-value: 0.0000

Predictor Timeframe: 350 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_300_its = -2.7227 * GIFT_BASKET_returns_from_350_its_ago
R-squared: 0.0764
p-value: 0.0000

Predictor Timeframe: 400 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_300_its = -3.1819 * GIFT_BASKET_returns_from_400_its_ago
R-squared: 0.1191
p-value: 0.0000

Predictor Timeframe: 500 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_300_its = -3.8551 * GIFT_BASKET_returns_from_500_its_ago
R-squared: 0.2160
p-value: 0.0000


Responder Timeframe: 350 iterations
Predictor Timeframe: 50 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_350_its = -1.1300 * GIFT_BASKET_returns_from_50_its_ago
R-squared: 0.0001
p-value: 0.0000

Predictor Timeframe: 75 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_350_its = -1.3332 * GIFT_BASKET_returns_from_75_its_ago
R-squared: 0.0026
p-value: 0.0000

Predictor Timeframe: 100 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_350_its = -1.4209 * GIFT_BASKET_returns_from_100_its_ago
R-squared: 0.0049
p-value: 0.0000

Predictor Timeframe: 150 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_350_its = -1.5160 * GIFT_BASKET_returns_from_150_its_ago
R-squared: 0.0094
p-value: 0.0000

Predictor Timeframe: 200 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_350_its = -2.0524 * GIFT_BASKET_returns_from_200_its_ago
R-squared: 0.0241
p-value: 0.0000

Predictor Timeframe: 250 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_350_its = -2.6936 * GIFT_BASKET_returns_from_250_its_ago
R-squared: 0.0508
p-value: 0.0000

Predictor Timeframe: 300 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_350_its = -3.1224 * GIFT_BASKET_returns_from_300_its_ago
R-squared: 0.0798
p-value: 0.0000

Predictor Timeframe: 350 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_350_its = -3.5481 * GIFT_BASKET_returns_from_350_its_ago
R-squared: 0.1197
p-value: 0.0000

Predictor Timeframe: 400 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_350_its = -4.0661 * GIFT_BASKET_returns_from_400_its_ago
R-squared: 0.1794
p-value: 0.0000

Predictor Timeframe: 500 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_350_its = -4.3791 * GIFT_BASKET_returns_from_500_its_ago
R-squared: 0.2555
p-value: 0.0000


Responder Timeframe: 400 iterations
Predictor Timeframe: 50 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_400_its = -1.7871 * GIFT_BASKET_returns_from_50_its_ago
R-squared: 0.0031
p-value: 0.0000

Predictor Timeframe: 75 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_400_its = -1.9876 * GIFT_BASKET_returns_from_75_its_ago
R-squared: 0.0075
p-value: 0.0000

Predictor Timeframe: 100 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_400_its = -2.0419 * GIFT_BASKET_returns_from_100_its_ago
R-squared: 0.0113
p-value: 0.0000

Predictor Timeframe: 150 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_400_its = -2.3792 * GIFT_BASKET_returns_from_150_its_ago
R-squared: 0.0239
p-value: 0.0000

Predictor Timeframe: 200 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_400_its = -3.1408 * GIFT_BASKET_returns_from_200_its_ago
R-squared: 0.0545
p-value: 0.0000

Predictor Timeframe: 250 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_400_its = -3.6258 * GIFT_BASKET_returns_from_250_its_ago
R-squared: 0.0865
p-value: 0.0000

Predictor Timeframe: 300 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_400_its = -4.1068 * GIFT_BASKET_returns_from_300_its_ago
R-squared: 0.1287
p-value: 0.0000

Predictor Timeframe: 350 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_400_its = -4.5822 * GIFT_BASKET_returns_from_350_its_ago
R-squared: 0.1860
p-value: 0.0000

Predictor Timeframe: 400 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_400_its = -4.9311 * GIFT_BASKET_returns_from_400_its_ago
R-squared: 0.2448
p-value: 0.0000

Predictor Timeframe: 500 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_400_its = -4.7615 * GIFT_BASKET_returns_from_500_its_ago
R-squared: 0.2791
p-value: 0.0000


Responder Timeframe: 500 iterations
Predictor Timeframe: 50 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_500_its = -3.6458 * GIFT_BASKET_returns_from_50_its_ago
R-squared: 0.0164
p-value: 0.0000

Predictor Timeframe: 75 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_500_its = -4.1452 * GIFT_BASKET_returns_from_75_its_ago
R-squared: 0.0329
p-value: 0.0000

Predictor Timeframe: 100 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_500_its = -4.3257 * GIFT_BASKET_returns_from_100_its_ago
R-squared: 0.0482
p-value: 0.0000

Predictor Timeframe: 150 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_500_its = -4.5030 * GIFT_BASKET_returns_from_150_its_ago
R-squared: 0.0766
p-value: 0.0000

Predictor Timeframe: 200 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_500_its = -5.1001 * GIFT_BASKET_returns_from_200_its_ago
R-squared: 0.1240
p-value: 0.0000

Predictor Timeframe: 250 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_500_its = -5.7214 * GIFT_BASKET_returns_from_250_its_ago
R-squared: 0.1847
p-value: 0.0000

Predictor Timeframe: 300 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_500_its = -6.0697 * GIFT_BASKET_returns_from_300_its_ago
R-squared: 0.2402
p-value: 0.0000

Predictor Timeframe: 350 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_500_its = -6.0061 * GIFT_BASKET_returns_from_350_its_ago
R-squared: 0.2709
p-value: 0.0000

Predictor Timeframe: 400 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_500_its = -5.7748 * GIFT_BASKET_returns_from_400_its_ago
R-squared: 0.2835
p-value: 0.0000

Predictor Timeframe: 500 iterations
Target Symbol: ORCHIDS
Learned Equation:
ORCHIDS_returns_in_500_its = -5.2917 * GIFT_BASKET_returns_from_500_its_ago
R-squared: 0.2920
p-value: 0.0000

# backtest

learned eq: 
ORCHIDS_returns_in_500_its = -5.2917 * GIFT_BASKET_returns_from_500_its_ago
R-squared: 0.2920

In [123]:
df

,timestamp,ORCHIDS,TRANSPORT_FEES,EXPORT_TARIFF,IMPORT_TARIFF,SUNLIGHT,HUMIDITY,DAY,CHOCOLATE,GIFT_BASKET,ROSES,STRAWBERRIES,COCONUT,COCONUT_COUPON
0,0,1098.25,0.9,10.5,-5.0,2100.0000,70.000000,1,7988.0,71114.5,14545.5,4030.5,10000.0,637.5
1,100,1098.25,0.9,9.5,-5.0,2099.7570,70.022710,1,7988.0,71114.0,14543.5,4030.5,9999.5,637.5
2,200,1096.75,0.9,9.5,-5.0,2099.5132,70.045395,1,7987.5,71115.5,14543.5,4030.0,9998.5,637.5
3,300,1097.00,0.9,9.5,-5.0,2099.2683,70.068030,1,7988.5,71123.5,14541.5,4030.0,9999.5,638.5
4,400,1097.25,0.9,9.5,-5.0,2099.0225,70.090640,1,7989.5,71132.5,14547.5,4030.0,9998.5,637.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,999600,1036.25,0.9,9.5,-5.0,2299.9436,69.935490,1,7885.5,70599.5,14418.0,4036.5,10136.5,682.5
9997,999700,1036.25,0.9,9.5,-5.0,2299.9556,69.951530,1,7885.5,70585.5,14421.5,4035.5,10134.5,681.5
9998,999800,1036.25,0.9,9.5,-5.0,2299.9690,69.967620,1,7887.5,70584.5,14419.0,4035.5,10135.0,681.5
9999,999900,1034.25,0.9,9.5,-5.0,2299.9840,69.983780,1,7887.5,70586.5,14422.5,4036.0,10135.0,682.5
10000,1000000,1035.25,0.9,9.5,-5.0,2300.0000,70.000000,1,NaN,NaN,NaN,NaN,NaN,NaN

In [134]:
df_backtest = df.copy()[['timestamp','ORCHIDS', 'GIFT_BASKET']]

In [135]:
df_backtest = get_prev_returns(df_backtest, 'GIFT_BASKET', 500)
df_backtest = get_future_returns(df_backtest, 'ORCHIDS', 500)

In [136]:
df_backtest = df_backtest.dropna()

In [137]:
df_backtest['ORCHIDS_pred_returns_in_500_its'] = df_backtest['GIFT_BASKET_returns_from_500_its_ago'] * -5.2917

In [304]:
take_threshold = -0.015
clear_threshold = -0.0005

In [305]:

df_backtest['orchids_signal'] = df_backtest.apply(lambda row: "SHORT" if row['ORCHIDS_pred_returns_in_500_its'] < take_threshold else "CLEAR" if row['ORCHIDS_pred_returns_in_500_its'] > clear_threshold else None,  axis=1)

In [308]:
df_backtest['last_orchids_signal'] = df_backtest['orchids_signal'].fillna(method='ffill')

/var/folders/qd/7_02v1xx1nx_p2rj9mxjqzzh0000gn/T/ipykernel_86789/1870579701.py:1: FutureWarning:

Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.

In [310]:
df_backtest.loc[df_backtest['last_orchids_signal'] == 'CLEAR', 'orchids_target_position'] = 0
df_backtest.loc[df_backtest['last_orchids_signal'] == 'SHORT', 'orchids_target_position'] = -100

In [311]:
df_backtest['orchids_target_position'] = df_backtest['orchids_target_position'].fillna(0)

In [313]:
df_backtest['orchids_target_position_change'] = df_backtest['orchids_target_position'].diff(1)

In [314]:
df_backtest['cash'] = -df_backtest['orchids_target_position_change'] * df_backtest['ORCHIDS']

In [315]:
df_backtest['cumulative_cash'] = df_backtest['cash'].cumsum()

In [316]:
df_backtest['position_mark'] = df_backtest['orchids_target_position'] * df_backtest['ORCHIDS']

In [317]:
df_backtest['pnl'] = df_backtest['position_mark'] + df_backtest['cumulative_cash']

In [318]:
df_backtest['pnl'].tail(3)

9498    8000.0
9499    8000.0
9500    8000.0
Name: pnl, dtype: float64

In [319]:

df_backtest.to_csv('backtest.csv', index=False)

In [329]:
import plotly.graph_objects as go

# Create the first trace for ORCHIDS_pred_returns_in_500_its
trace1 = go.Scatter(
    x=df_backtest['timestamp'],
    y=df_backtest['ORCHIDS_pred_returns_in_500_its'],
    name='ORCHIDS Predicted Returns',
    yaxis='y1'
)

# Create the second trace for pnl
trace2 = go.Scatter(
    x=df_backtest['timestamp'],
    y=df_backtest['pnl'],
    name='PnL',
    yaxis='y2'
)

# Create the third trace for ORCHIDS
trace3 = go.Scatter(
    x=df_backtest['timestamp'],
    y=df_backtest['ORCHIDS'],
    name='ORCHIDS',
    yaxis='y3'
)

# Create the layout for the graph
layout = go.Layout(
    title='ORCHIDS, Predicted Returns, and PnL',
    xaxis=dict(title='Timestamp'),
    yaxis=dict(
        title='ORCHIDS Predicted Returns',
        side='left'
    ),
    yaxis2=dict(
        title='PnL',
        side='right',
        overlaying='y'
    ),
    yaxis3=dict(
        title='ORCHIDS',
        side='right',
        overlaying='y',
        position=0.95
    )
)

# Create the figure and add the traces and layout
fig = go.Figure(data=[trace1, trace2, trace3], layout=layout)

# Show the plot
fig.show()

In [330]:
0.02*1000

20.0

In [331]:
20 - 5

15

In [334]:
import io

# backtest on other days

In [340]:
def _process_data_(file):
    with open(file, 'r') as file:
        log_content = file.read()
    sections = log_content.split('Sandbox logs:')[1].split('Activities log:')
    sandbox_log =  sections[0].strip()
    activities_log = sections[1].split('Trade History:')[0]
    # sandbox_log_list = [json.loads(line) for line in sandbox_log.split('\n')]
    trade_history =  json.loads(sections[1].split('Trade History:')[1])
    # sandbox_log_df = pd.DataFrame(sandbox_log_list)
    market_data_df = pd.read_csv(io.StringIO(activities_log), sep=";", header=0)
    trade_history_df = pd.json_normalize(trade_history)
    return market_data_df, trade_history_df

In [337]:
df3, _ = _process_data_('./round-4-island-data-bottle/round_3_results.log')

In [339]:
df_day_3

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
0,1,0,GIFT_BASKET,71108,12,71107.0,27.0,NaN,NaN,71121,12,71122.0,27.0,NaN,NaN,71114.5,0.0
1,1,0,CHOCOLATE,7987,104,NaN,NaN,NaN,NaN,7989,104,NaN,NaN,NaN,NaN,7988.0,0.0
2,1,0,ROSES,14545,27,14544.0,34.0,NaN,NaN,14546,61,NaN,NaN,NaN,NaN,14545.5,0.0
3,1,0,STRAWBERRIES,4030,237,NaN,NaN,NaN,NaN,4031,237,NaN,NaN,NaN,NaN,4030.5,0.0
4,1,100,STRAWBERRIES,4030,52,4029.0,137.0,NaN,NaN,4031,189,NaN,NaN,NaN,NaN,4030.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,1,999800,STRAWBERRIES,4035,211,NaN,NaN,NaN,NaN,4036,80,4037.0,131.0,NaN,NaN,4035.5,0.0
39996,1,999900,ROSES,14422,70,NaN,NaN,NaN,NaN,14423,70,NaN,NaN,NaN,NaN,14422.5,0.0
39997,1,999900,STRAWBERRIES,4035,204,NaN,NaN,NaN,NaN,4037,204,NaN,NaN,NaN,NaN,4036.0,0.0
39998,1,999900,GIFT_BASKET,70580,15,70579.0,21.0,NaN,NaN,70593,15,70594.0,21.0,NaN,NaN,70586.5,0.0
39999,1,999900,CHOCOLATE,7887,44,7886.0,75.0,NaN,NaN,7888,119,NaN,NaN,NaN,NaN,7887.5,0.0

In [341]:
file_name = f"./round-{3}-island-data-bottle/prices_round_{3}_day_0.csv"
df_round_3 = pd.read_csv(file_name, sep=';')

file_name = f"./round-{2}-island-data-bottle/prices_round_{2}_day_0.csv"
df_round_2 = pd.read_csv(file_name, sep=';')

In [349]:
df_round_2 = df_round_2[['timestamp', 'ORCHIDS']]

In [350]:
df_round_2

       timestamp  ORCHIDS
0              0  1111.75
1            100  1111.75
2            200  1109.75
3            300  1109.25
4            400  1110.75
...          ...      ...
9996      999600   988.25
9997      999700   988.00
9998      999800   988.75
9999      999900   986.75
10000    1000000   985.75

[10001 rows x 2 columns]

In [351]:
df_round_3 = df_round_3.pivot(columns='product', index='timestamp', values='mid_price').reset_index()

In [353]:
df = df_round_2.merge(df_round_3, on='timestamp', how='inner')

In [355]:
df_backtest = df.copy()[['timestamp','ORCHIDS', 'GIFT_BASKET']]

In [356]:
df_backtest = get_prev_returns(df_backtest, 'GIFT_BASKET', 500)
df_backtest = get_future_returns(df_backtest, 'ORCHIDS', 500)

In [357]:
df_backtest = df_backtest.dropna()

In [358]:
df_backtest['ORCHIDS_pred_returns_in_500_its'] = df_backtest['GIFT_BASKET_returns_from_500_its_ago'] * -5.2917

In [359]:
df_backtest.describe()

,timestamp,ORCHIDS,GIFT_BASKET,GIFT_BASKET_returns_from_500_its_ago,ORCHIDS_returns_in_500_its,ORCHIDS_pred_returns_in_500_its
count,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000
mean,499950.000000,1039.608000,71213.262167,-0.000276,-0.005087,0.001460
std,259822.054491,42.918707,164.912808,0.002275,0.020943,0.012037
min,50000.000000,960.750000,70823.500000,-0.005576,-0.052206,-0.036910
25%,274975.000000,1003.250000,71099.500000,-0.001910,-0.019847,-0.005770
50%,499950.000000,1039.250000,71219.500000,-0.000504,-0.010852,0.002665
75%,724925.000000,1079.250000,71319.500000,0.001090,0.011857,0.010109
max,949900.000000,1121.250000,71586.500000,0.006975,0.044502,0.029504

In [360]:
df_backtest

,timestamp,ORCHIDS,GIFT_BASKET,GIFT_BASKET_returns_from_500_its_ago,ORCHIDS_returns_in_500_its,ORCHIDS_pred_returns_in_500_its
500,50000,1118.00,71414.5,0.000834,-0.019902,-0.004413
501,50100,1117.75,71425.5,0.001065,-0.019682,-0.005637
502,50200,1117.75,71414.5,0.000946,-0.019682,-0.005006
503,50300,1119.25,71403.5,0.000743,-0.022336,-0.003931
504,50400,1118.75,71409.5,0.000953,-0.022123,-0.005044
...,...,...,...,...,...,...
9495,949500,1016.25,71035.5,0.000437,-0.026568,-0.002310
9496,949600,1016.25,71039.5,0.000408,-0.027552,-0.002161
9497,949700,1016.00,71039.0,0.000303,-0.027559,-0.001602
9498,949800,1017.75,71038.5,0.000246,-0.028494,-0.001304
9499,949900,1017.25,71048.5,0.000437,-0.029983,-0.002310

In [361]:
take_threshold = -0.015
clear_threshold = -0.0005

In [362]:

df_backtest['orchids_signal'] = df_backtest.apply(lambda row: "SHORT" if row['ORCHIDS_pred_returns_in_500_its'] < take_threshold else "CLEAR" if row['ORCHIDS_pred_returns_in_500_its'] > clear_threshold else None,  axis=1)

In [363]:
df_backtest

,timestamp,ORCHIDS,GIFT_BASKET,GIFT_BASKET_returns_from_500_its_ago,ORCHIDS_returns_in_500_its,ORCHIDS_pred_returns_in_500_its,orchids_signal
500,50000,1118.00,71414.5,0.000834,-0.019902,-0.004413,None
501,50100,1117.75,71425.5,0.001065,-0.019682,-0.005637,None
502,50200,1117.75,71414.5,0.000946,-0.019682,-0.005006,None
503,50300,1119.25,71403.5,0.000743,-0.022336,-0.003931,None
504,50400,1118.75,71409.5,0.000953,-0.022123,-0.005044,None
...,...,...,...,...,...,...,...
9495,949500,1016.25,71035.5,0.000437,-0.026568,-0.002310,None
9496,949600,1016.25,71039.5,0.000408,-0.027552,-0.002161,None
9497,949700,1016.00,71039.0,0.000303,-0.027559,-0.001602,None
9498,949800,1017.75,71038.5,0.000246,-0.028494,-0.001304,None
9499,949900,1017.25,71048.5,0.000437,-0.029983,-0.002310,None

In [364]:
df_backtest['orchids_signal'].value_counts()

orchids_signal
CLEAR    5444
SHORT     933
Name: count, dtype: int64

In [365]:
df_backtest['last_orchids_signal'] = df_backtest['orchids_signal'].fillna(method='ffill')

/var/folders/qd/7_02v1xx1nx_p2rj9mxjqzzh0000gn/T/ipykernel_86789/1870579701.py:1: FutureWarning:

Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.

In [366]:
df_backtest['last_orchids_signal'].value_counts()

last_orchids_signal
CLEAR    7181
SHORT    1800
Name: count, dtype: int64

In [367]:
df_backtest.loc[df_backtest['last_orchids_signal'] == 'CLEAR', 'orchids_target_position'] = 0
df_backtest.loc[df_backtest['last_orchids_signal'] == 'SHORT', 'orchids_target_position'] = -100

In [368]:
df_backtest['orchids_target_position'] = df_backtest['orchids_target_position'].fillna(0)

In [369]:
df_backtest

,timestamp,ORCHIDS,GIFT_BASKET,GIFT_BASKET_returns_from_500_its_ago,ORCHIDS_returns_in_500_its,ORCHIDS_pred_returns_in_500_its,orchids_signal,last_orchids_signal,orchids_target_position
500,50000,1118.00,71414.5,0.000834,-0.019902,-0.004413,None,None,0.0
501,50100,1117.75,71425.5,0.001065,-0.019682,-0.005637,None,None,0.0
502,50200,1117.75,71414.5,0.000946,-0.019682,-0.005006,None,None,0.0
503,50300,1119.25,71403.5,0.000743,-0.022336,-0.003931,None,None,0.0
504,50400,1118.75,71409.5,0.000953,-0.022123,-0.005044,None,None,0.0
...,...,...,...,...,...,...,...,...,...
9495,949500,1016.25,71035.5,0.000437,-0.026568,-0.002310,None,CLEAR,0.0
9496,949600,1016.25,71039.5,0.000408,-0.027552,-0.002161,None,CLEAR,0.0
9497,949700,1016.00,71039.0,0.000303,-0.027559,-0.001602,None,CLEAR,0.0
9498,949800,1017.75,71038.5,0.000246,-0.028494,-0.001304,None,CLEAR,0.0
9499,949900,1017.25,71048.5,0.000437,-0.029983,-0.002310,None,CLEAR,0.0

In [370]:
df_backtest['orchids_target_position_change'] = df_backtest['orchids_target_position'].diff(1)

In [371]:
df_backtest['cash'] = -df_backtest['orchids_target_position_change'] * df_backtest['ORCHIDS']

In [372]:
df_backtest['cumulative_cash'] = df_backtest['cash'].cumsum()

In [373]:
df_backtest['position_mark'] = df_backtest['orchids_target_position'] * df_backtest['ORCHIDS']

In [374]:
df_backtest['pnl'] = df_backtest['position_mark'] + df_backtest['cumulative_cash']

In [375]:
df_backtest['pnl'].tail(3)

9497    6425.0
9498    6425.0
9499    6425.0
Name: pnl, dtype: float64

In [354]:
df

      timestamp  ORCHIDS  CHOCOLATE  GIFT_BASKET    ROSES  STRAWBERRIES
0             0  1111.75     8000.0      71355.0  15000.0        4000.0
1           100  1111.75     8001.5      71349.5  15000.0        3999.5
2           200  1109.75     8001.0      71347.0  15000.5        3999.5
3           300  1109.25     8002.5      71350.5  15000.0        3999.5
4           400  1110.75     8002.0      71341.5  14997.5        3999.5
...         ...      ...        ...          ...      ...           ...
9995     999500   989.25     7987.5      71141.5  14543.5        4031.0
9996     999600   988.25     7988.5      71134.5  14548.0        4031.0
9997     999700   988.00     7987.5      71128.5  14546.5        4031.0
9998     999800   988.75     7989.5      71138.0  14546.5        4031.0
9999     999900   986.75     7988.0      71122.5  14550.5        4030.5

[10000 rows x 6 columns]

In [376]:
import plotly.graph_objects as go

# Create the first trace for ORCHIDS_pred_returns_in_500_its
trace1 = go.Scatter(
    x=df_backtest['timestamp'],
    y=df_backtest['ORCHIDS_pred_returns_in_500_its'],
    name='ORCHIDS Predicted Returns',
    yaxis='y1'
)

# Create the second trace for pnl
trace2 = go.Scatter(
    x=df_backtest['timestamp'],
    y=df_backtest['pnl'],
    name='PnL',
    yaxis='y2'
)

# Create the third trace for ORCHIDS
trace3 = go.Scatter(
    x=df_backtest['timestamp'],
    y=df_backtest['ORCHIDS'],
    name='ORCHIDS',
    yaxis='y3'
)

# Create the layout for the graph
layout = go.Layout(
    title='ORCHIDS, Predicted Returns, and PnL',
    xaxis=dict(title='Timestamp'),
    yaxis=dict(
        title='ORCHIDS Predicted Returns',
        side='left'
    ),
    yaxis2=dict(
        title='PnL',
        side='right',
        overlaying='y'
    ),
    yaxis3=dict(
        title='ORCHIDS',
        side='right',
        overlaying='y',
        position=0.95
    )
)

# Create the figure and add the traces and layout
fig = go.Figure(data=[trace1, trace2, trace3], layout=layout)

# Show the plot
fig.show()